//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_Ref_KunstKuenstler
    {
        public T_AP_Ref_KunstKuenstler()
        {
            this.T_ZO_AP_Kunst_AP_Ref_KunstKuenstler = new HashSet<T_ZO_AP_Kunst_AP_Ref_KunstKuenstler>();
        }
    
        public System.Guid KK_UID { get; set; }
        public Nullable<int> KK_Code { get; set; }
        public string KK_Kurz_DE { get; set; }
        public string KK_Kurz_FR { get; set; }
        public string KK_Kurz_IT { get; set; }
        public string KK_Kurz_EN { get; set; }
        public string KK_Lang_DE { get; set; }
        public string KK_Lang_FR { get; set; }
        public string KK_Lang_IT { get; set; }
        public string KK_Lang_EN { get; set; }
        public int KK_Status { get; set; }
        public int KK_Sort { get; set; }
        public Nullable<int> KK_StylizerBack { get; set; }
        public Nullable<int> KK_StylizerPattern { get; set; }
        public Nullable<int> KK_StylizerLine { get; set; }
        public bool KK_IsDefault { get; set; }
        public Nullable<System.DateTime> KK_DatumMut { get; set; }
        public string KK_DatumUser { get; set; }
        public string KK_Biografie { get; set; }
        public Nullable<int> KK_Geburtsjahr { get; set; }
        public Nullable<int> KK_Todesjahr { get; set; }
        public string KK_Geburtsort { get; set; }
        public string KK_Todesort { get; set; }
        public string KK_Alias { get; set; }
        public Nullable<int> KK_Geburtstag { get; set; }
        public Nullable<int> KK_Geburtsmonat { get; set; }
        public Nullable<int> KK_Todestag { get; set; }
        public Nullable<int> KK_Todesmonat { get; set; }
    
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
        public virtual T_AP_Ref_Ort T_AP_Ref_Ort { get; set; }
        public virtual T_AP_Ref_Ort T_AP_Ref_Ort1 { get; set; }
        public virtual T_SYS_ApertureColorToHex T_SYS_ApertureColorToHex { get; set; }
        public virtual T_SYS_Ref_Geschlecht T_SYS_Ref_Geschlecht { get; set; }
        public virtual ICollection<T_ZO_AP_Kunst_AP_Ref_KunstKuenstler> T_ZO_AP_Kunst_AP_Ref_KunstKuenstler { get; set; }
    }
}
