//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeedEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_EmailVersand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_AP_EmailVersand()
        {
            this.T_AP_Ref_EmailAttachment = new HashSet<T_AP_Ref_EmailAttachment>();
        }
    
        public System.Guid EMAIL_UID { get; set; }
        public Nullable<System.Guid> EMAIL_ETC_UID { get; set; }
        public string EMAIL_Text { get; set; }
        public string EMAIL_Titel { get; set; }
        public string EMAIL_From { get; set; }
        public string EMAIL_To { get; set; }
        public string EMAIL_CC { get; set; }
        public Nullable<System.DateTime> EMAIL_Datum { get; set; }
        public int EMAIL_MDT_ID { get; set; }
        public bool EMAIL_Send { get; set; }
        public int EMAIL_Status { get; set; }
    
        public virtual T_AP_Ref_EmailtextKategorie T_AP_Ref_EmailtextKategorie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_AP_Ref_EmailAttachment> T_AP_Ref_EmailAttachment { get; set; }
    }
}
