//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeedEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_Ref_ZylinderStatus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_AP_Ref_ZylinderStatus()
        {
            this.T_AP_Zylinder = new HashSet<T_AP_Zylinder>();
        }
    
        public System.Guid ZSTA_UID { get; set; }
        public int ZSTA_MDT_ID { get; set; }
        public Nullable<int> ZSTA_Code { get; set; }
        public string ZSTA_Kurz_DE { get; set; }
        public string ZSTA_Kurz_FR { get; set; }
        public string ZSTA_Kurz_IT { get; set; }
        public string ZSTA_Kurz_EN { get; set; }
        public string ZSTA_Lang_DE { get; set; }
        public string ZSTA_Lang_FR { get; set; }
        public string ZSTA_Lang_IT { get; set; }
        public string ZSTA_Lang_EN { get; set; }
        public int ZSTA_Status { get; set; }
        public int ZSTA_Sort { get; set; }
        public Nullable<int> ZSTA_StylizerFore { get; set; }
        public Nullable<int> ZSTA_StylizerBack { get; set; }
        public Nullable<int> ZSTA_StylizerPattern { get; set; }
        public Nullable<int> ZSTA_StylizerLine { get; set; }
        public bool ZSTA_IsDefault { get; set; }
        public Nullable<System.DateTime> ZSTA_DatumMut { get; set; }
        public string ZSTA_DatumUser { get; set; }
    
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_AP_Zylinder> T_AP_Zylinder { get; set; }
    }
}
