//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeedEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_StichtagVisualisierung
    {
        public string ST_User { get; set; }
        public string ST_Zeichnung { get; set; }
        public System.DateTime ST_Stichtag { get; set; }
    }
}
