//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeedEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_Anschluss
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_AP_Anschluss()
        {
            this.T_AP_Anschluss_History = new HashSet<T_AP_Anschluss_History>();
            this.T_ZO_AP_Anschluss_DWG = new HashSet<T_ZO_AP_Anschluss_DWG>();
        }
    
        public System.Guid AN_UID { get; set; }
        public int AN_MDT_ID { get; set; }
        public Nullable<System.Guid> AN_DO_UID { get; set; }
        public Nullable<System.Guid> AN_ANKAT_UID { get; set; }
        public Nullable<System.Guid> AN_ANT_UID { get; set; }
        public Nullable<System.Guid> AN_AKBT_UID { get; set; }
        public Nullable<System.Guid> AN_ASWI_UID { get; set; }
        public Nullable<System.Guid> AN_AVER_UID { get; set; }
        public string AN_Bezeichnung { get; set; }
        public string AN_Anschluss { get; set; }
        public bool AN_IsBelegt { get; set; }
        public string AN_ApertureKey { get; set; }
        public string AN_Nr { get; set; }
        public int AN_Port { get; set; }
        public string AN_Bemerkung { get; set; }
        public System.DateTime AN_DatumVon { get; set; }
        public System.DateTime AN_DatumBis { get; set; }
        public int AN_Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_AP_Anschluss_History> T_AP_Anschluss_History { get; set; }
        public virtual T_AP_Dose T_AP_Dose { get; set; }
        public virtual T_AP_Ref_AnschlussKabelTyp T_AP_Ref_AnschlussKabelTyp { get; set; }
        public virtual T_AP_Ref_AnschlussKategorie T_AP_Ref_AnschlussKategorie { get; set; }
        public virtual T_AP_Ref_AnschlussSwitch T_AP_Ref_AnschlussSwitch { get; set; }
        public virtual T_AP_Ref_AnschlussTyp T_AP_Ref_AnschlussTyp { get; set; }
        public virtual T_AP_Ref_AnschlussVerteiler T_AP_Ref_AnschlussVerteiler { get; set; }
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ZO_AP_Anschluss_DWG> T_ZO_AP_Anschluss_DWG { get; set; }
    }
}
