//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeedEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_Anlage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_AP_Anlage()
        {
            this.T_AP_Anlage_History = new HashSet<T_AP_Anlage_History>();
            this.T_SYS_Anlagerechte = new HashSet<T_SYS_Anlagerechte>();
            this.T_TM_Tasks_Planung = new HashSet<T_TM_Tasks_Planung>();
            this.T_TM_Tasks = new HashSet<T_TM_Tasks>();
            this.T_UPS_Rechnungskontrolle = new HashSet<T_UPS_Rechnungskontrolle>();
            this.T_ZO_AP_Anlage_DWG = new HashSet<T_ZO_AP_Anlage_DWG>();
        }
    
        public System.Guid AL_UID { get; set; }
        public int AL_MDT_ID { get; set; }
        public Nullable<System.Guid> AL_VAR_UID { get; set; }
        public Nullable<System.Guid> AL_RM_UID { get; set; }
        public Nullable<System.Guid> AL_ADR_UID { get; set; }
        public System.Guid AL_AK_UID { get; set; }
        public string AL_ApertureKey { get; set; }
        public string AL_Nr { get; set; }
        public string AL_Hersteller { get; set; }
        public string AL_Modell { get; set; }
        public string AL_Typ { get; set; }
        public string AL_TypenNr { get; set; }
        public int AL_Baujahr { get; set; }
        public string AL_SerienNr { get; set; }
        public string AL_Beschreibung { get; set; }
        public string AL_Bemerkung { get; set; }
        public System.DateTime AL_DatumVon { get; set; }
        public System.DateTime AL_DatumBis { get; set; }
        public int AL_Status { get; set; }
        public Nullable<System.DateTime> AL_MutDate { get; set; }
        public string AL_MutUser { get; set; }
        public Nullable<System.Guid> AL_DETAIL_BKP_UID { get; set; }
        public Nullable<double> AL_DETAIL_Leistung { get; set; }
        public Nullable<System.Guid> AL_DETAIL_AET_UID { get; set; }
        public Nullable<int> AL_DETAIL_BaujahrBrenner { get; set; }
        public Nullable<double> AL_DETAIL_Energiemenge { get; set; }
        public Nullable<double> AL_DETAIL_EBF { get; set; }
        public Nullable<int> AL_DETAIL_AP { get; set; }
        public Nullable<double> AL_DETAIL_NGF { get; set; }
        public Nullable<double> AL_DETAIL_SV_Eigenprod { get; set; }
        public Nullable<double> AL_DETAIL_SV_Fremdprod { get; set; }
        public Nullable<double> AL_DETAIL_SV_Wiederholung { get; set; }
        public Nullable<System.Guid> AL_DETAIL_AKM_UID { get; set; }
        public Nullable<System.Guid> AL_DETAIL_ARK_UID { get; set; }
        public Nullable<double> AL_DETAIL_InhaltSpeicher { get; set; }
        public Nullable<double> AL_DETAIL_Zuluft { get; set; }
        public Nullable<System.Guid> AL_DETAIL_AWRG_UID { get; set; }
        public Nullable<double> AL_DETAIL_Luftkuehler { get; set; }
        public Nullable<double> AL_DETAIL_Befeuchtung { get; set; }
        public Nullable<System.Guid> AL_DETAIL_ABA_UID { get; set; }
        public Nullable<double> AL_DETAIL_Nutzlast { get; set; }
        public Nullable<System.Guid> AL_BKP_UID { get; set; }
        public string AL_DETAIL_Nutzebene { get; set; }
        public Nullable<System.Guid> AL_DETAIL_ABF_UID { get; set; }
        public Nullable<double> AL_DETAIL_Abluft { get; set; }
        public Nullable<double> AL_DETAIL_Wasser { get; set; }
        public Nullable<System.Guid> AL_SO_UID { get; set; }
        public Nullable<System.Guid> AL_GB_UID { get; set; }
        public Nullable<System.Guid> AL_GS_UID { get; set; }
        public Nullable<double> AL_DETAIL_Uwert_Fenster { get; set; }
        public Nullable<double> AL_DETAIL_Uwert_Aussenwand { get; set; }
        public Nullable<double> AL_DETAIL_Uwert_Dach { get; set; }
        public Nullable<double> AL_DETAIL_Uwert_Boden { get; set; }
        public Nullable<System.Guid> AL_AL_UID { get; set; }
        public Nullable<System.Guid> AL_MASTER_UID { get; set; }
        public string AL_MASTER_TYP { get; set; }
        public string AL_DETAIL_LBH { get; set; }
        public Nullable<System.DateTime> AL_Abnahmedatum { get; set; }
        public Nullable<System.DateTime> AL_GarantieBis { get; set; }
        public int AL_Lebensdauer { get; set; }
        public int AL_Anschaffungspreis { get; set; }
        public Nullable<System.Guid> AL_AKV_UID { get; set; }
        public int AL_BE_ID { get; set; }
        public bool AL_IsPraeventiv { get; set; }
        public bool AL_IsInstandhaltung { get; set; }
        public bool AL_IsFehlerbehebung { get; set; }
        public bool AL_IsGesVorschriften { get; set; }
        public bool AL_IsRelevantNebenkosten { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_AP_Anlage_History> T_AP_Anlage_History { get; set; }
        public virtual T_AP_Gebaeude T_AP_Gebaeude { get; set; }
        public virtual T_AP_Geschoss T_AP_Geschoss { get; set; }
        public virtual T_AP_Raum T_AP_Raum { get; set; }
        public virtual T_AP_Ref_AnlageKategorie T_AP_Ref_AnlageKategorie { get; set; }
        public virtual T_AP_Ref_AnlageKategorieVerfuegbarkeit T_AP_Ref_AnlageKategorieVerfuegbarkeit { get; set; }
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
        public virtual T_AP_Standort T_AP_Standort { get; set; }
        public virtual T_AV_Adressen T_AV_Adressen { get; set; }
        public virtual T_VAR_Variante T_VAR_Variante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_SYS_Anlagerechte> T_SYS_Anlagerechte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_TM_Tasks_Planung> T_TM_Tasks_Planung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_TM_Tasks> T_TM_Tasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_UPS_Rechnungskontrolle> T_UPS_Rechnungskontrolle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ZO_AP_Anlage_DWG> T_ZO_AP_Anlage_DWG { get; set; }
    }
}
