//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeedEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_Ref_Region
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_AP_Ref_Region()
        {
            this.T_AP_Ref_Ort = new HashSet<T_AP_Ref_Ort>();
            this.T_AV_Adressen = new HashSet<T_AV_Adressen>();
        }
    
        public System.Guid RG_UID { get; set; }
        public int RG_MDT_ID { get; set; }
        public Nullable<System.Guid> RG_LD_UID { get; set; }
        public string RG_Code { get; set; }
        public string RG_Kurz_DE { get; set; }
        public string RG_Kurz_FR { get; set; }
        public string RG_Kurz_IT { get; set; }
        public string RG_Kurz_EN { get; set; }
        public string RG_Lang_DE { get; set; }
        public string RG_Lang_FR { get; set; }
        public string RG_Lang_IT { get; set; }
        public string RG_Lang_EN { get; set; }
        public int RG_Status { get; set; }
        public int RG_Sort { get; set; }
        public Nullable<int> RG_StylizerBack { get; set; }
        public Nullable<int> RG_StylizerFore { get; set; }
        public Nullable<int> RG_StylizerPattern { get; set; }
        public Nullable<int> RG_StylizerLine { get; set; }
        public bool RG_IsDefault { get; set; }
        public Nullable<System.DateTime> RG_DatumMut { get; set; }
        public string RG_DatumUser { get; set; }
        public Nullable<decimal> RG_GM_Lat { get; set; }
        public Nullable<decimal> RG_GM_Lng { get; set; }
    
        public virtual T_AP_Ref_Land T_AP_Ref_Land { get; set; }
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_AP_Ref_Ort> T_AP_Ref_Ort { get; set; }
        public virtual T_SYS_ApertureColorToHex T_SYS_ApertureColorToHex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_AV_Adressen> T_AV_Adressen { get; set; }
    }
}
