//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeedEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_Ref_NutzungsartGruppe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_AP_Ref_NutzungsartGruppe()
        {
            this.T_AP_Ref_Nutzungsart = new HashSet<T_AP_Ref_Nutzungsart>();
        }
    
        public System.Guid NAG_UID { get; set; }
        public int NAG_MDT_ID { get; set; }
        public Nullable<int> NAG_Code { get; set; }
        public string NAG_Kurz_DE { get; set; }
        public string NAG_Kurz_FR { get; set; }
        public string NAG_Kurz_IT { get; set; }
        public string NAG_Kurz_EN { get; set; }
        public string NAG_Lang_DE { get; set; }
        public string NAG_Lang_FR { get; set; }
        public string NAG_Lang_IT { get; set; }
        public string NAG_Lang_EN { get; set; }
        public int NAG_Status { get; set; }
        public int NAG_Sort { get; set; }
        public Nullable<int> NAG_StylizerFore { get; set; }
        public Nullable<int> NAG_StylizerBack { get; set; }
        public Nullable<int> NAG_StylizerPattern { get; set; }
        public Nullable<int> NAG_StylizerLine { get; set; }
        public bool NAG_IsDefault { get; set; }
        public Nullable<System.DateTime> NAG_DatumMut { get; set; }
        public string NAG_DatumUser { get; set; }
        public double NAG_Mietzins { get; set; }
    
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_AP_Ref_Nutzungsart> T_AP_Ref_Nutzungsart { get; set; }
        public virtual T_SYS_ApertureColorToHex T_SYS_ApertureColorToHex { get; set; }
    }
}
