//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeedEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_Ref_PersonalKategorie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_AP_Ref_PersonalKategorie()
        {
            this.T_AP_Kontakte = new HashSet<T_AP_Kontakte>();
            this.T_ZO_AP_Kontakte_AP_Ref_PersonalKategorie = new HashSet<T_ZO_AP_Kontakte_AP_Ref_PersonalKategorie>();
        }
    
        public System.Guid PK_UID { get; set; }
        public Nullable<int> PK_MDT_ID { get; set; }
        public Nullable<int> PK_Code { get; set; }
        public string PK_Kurz_DE { get; set; }
        public string PK_Kurz_FR { get; set; }
        public string PK_Kurz_IT { get; set; }
        public string PK_Kurz_EN { get; set; }
        public string PK_Lang_DE { get; set; }
        public string PK_Lang_FR { get; set; }
        public string PK_Lang_IT { get; set; }
        public string PK_Lang_EN { get; set; }
        public int PK_Status { get; set; }
        public int PK_Sort { get; set; }
        public Nullable<int> PK_StylizerFore { get; set; }
        public Nullable<int> PK_StylizerBack { get; set; }
        public Nullable<int> PK_StylizerPattern { get; set; }
        public Nullable<int> PK_StylizerLine { get; set; }
        public bool PK_IsDefault { get; set; }
        public Nullable<System.DateTime> PK_DatumMut { get; set; }
        public string PK_DatumUser { get; set; }
        public Nullable<bool> PK_IsFromOdis { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_AP_Kontakte> T_AP_Kontakte { get; set; }
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
        public virtual T_SYS_ApertureColorToHex T_SYS_ApertureColorToHex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ZO_AP_Kontakte_AP_Ref_PersonalKategorie> T_ZO_AP_Kontakte_AP_Ref_PersonalKategorie { get; set; }
    }
}
