//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeedEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AV_Ref_AdresseRollen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_AV_Ref_AdresseRollen()
        {
            this.T_SYS_AdresseRollenrechte = new HashSet<T_SYS_AdresseRollenrechte>();
            this.T_ZO_AV_Adresse_AV_Ref_AdresseRollen = new HashSet<T_ZO_AV_Adresse_AV_Ref_AdresseRollen>();
        }
    
        public System.Guid AR_UID { get; set; }
        public Nullable<int> AR_Code { get; set; }
        public string AR_Kurz_DE { get; set; }
        public string AR_Kurz_FR { get; set; }
        public string AR_Kurz_IT { get; set; }
        public string AR_Kurz_EN { get; set; }
        public string AR_Lang_DE { get; set; }
        public string AR_Lang_FR { get; set; }
        public string AR_Lang_IT { get; set; }
        public string AR_Lang_EN { get; set; }
        public int AR_Status { get; set; }
        public int AR_Sort { get; set; }
        public Nullable<int> AR_StylizerFore { get; set; }
        public Nullable<int> AR_StylizerBack { get; set; }
        public Nullable<int> AR_StylizerPattern { get; set; }
        public Nullable<int> AR_StylizerLine { get; set; }
        public bool AR_IsDefault { get; set; }
        public Nullable<System.DateTime> AR_DatumMut { get; set; }
        public string AR_DatumUser { get; set; }
    
        public virtual T_SYS_ApertureColorToHex T_SYS_ApertureColorToHex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_SYS_AdresseRollenrechte> T_SYS_AdresseRollenrechte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ZO_AV_Adresse_AV_Ref_AdresseRollen> T_ZO_AV_Adresse_AV_Ref_AdresseRollen { get; set; }
    }
}
