//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeedEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AV_AdresseKontaktpersonen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_AV_AdresseKontaktpersonen()
        {
            this.T_VM_Vertraege = new HashSet<T_VM_Vertraege>();
        }
    
        public System.Guid AKP_UID { get; set; }
        public Nullable<System.Guid> AKP_ADR_UID { get; set; }
        public string AKP_Name { get; set; }
        public string AKP_Vorname { get; set; }
        public string AKP_Telefon { get; set; }
        public string AKP_Mobile { get; set; }
        public string AKP_Email { get; set; }
        public string AKP_Bemerkung { get; set; }
        public int AKP_Status { get; set; }
    
        public virtual T_AV_Adressen T_AV_Adressen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_VM_Vertraege> T_VM_Vertraege { get; set; }
    }
}
