//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeedEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DMS_SYS_DokumentTyp
    {
        public System.Guid SYS_DT_UID { get; set; }
        public Nullable<int> SYS_DT_Code { get; set; }
        public string SYS_DT_Typ { get; set; }
        public string SYS_DT_Endung { get; set; }
        public int SYS_Status { get; set; }
    }
}
