//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeedEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DMS_Projekt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_DMS_Projekt()
        {
            this.T_DMS_Navigation = new HashSet<T_DMS_Navigation>();
            this.T_DMS_Projekt_History = new HashSet<T_DMS_Projekt_History>();
        }
    
        public System.Guid PJ_UID { get; set; }
        public Nullable<System.Guid> PJ_NT_UID { get; set; }
        public string PJ_Nr { get; set; }
        public string PJ_Bezeichnung { get; set; }
        public string PJ_Beschreibung { get; set; }
        public string PJ_Bemerkung { get; set; }
        public System.DateTime PJ_DatumVon { get; set; }
        public System.DateTime PJ_DatumBis { get; set; }
        public int PJ_Status { get; set; }
        public Nullable<System.DateTime> PJ_MutDate { get; set; }
        public string PJ_MutUser { get; set; }
        public int PJ_Sort { get; set; }
        public string PJ_Link { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_DMS_Navigation> T_DMS_Navigation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_DMS_Projekt_History> T_DMS_Projekt_History { get; set; }
        public virtual T_DMS_Ref_NodeType T_DMS_Ref_NodeType { get; set; }
    }
}
