//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeedEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EM_EnergiePositionen
    {
        public System.Guid EMEP_UID { get; set; }
        public string EMEP_Objekt { get; set; }
        public string EMEP_Tabelle { get; set; }
        public string EMEP_FeldPrfx { get; set; }
        public Nullable<System.Guid> EMEP_Objekt_UID { get; set; }
        public int EMEP_Jahr { get; set; }
        public double EMEP_Waerme_Oel { get; set; }
        public double EMEP_Waerme_Gas { get; set; }
        public double EMEP_Waerme_Holz { get; set; }
        public double EMEP_Waerme_Fern { get; set; }
        public double EMEP_Waerme_Abwaerme { get; set; }
        public double EMEP_Waerme_Elektrizitaet { get; set; }
        public double EMEP_Kaelte { get; set; }
        public double EMEP_Elektrizitaet { get; set; }
        public double EMEP_Wasser { get; set; }
        public int EMEP_Status { get; set; }
        public string EMEP_MutUser { get; set; }
        public Nullable<System.DateTime> EMEP_MutDate { get; set; }
        public string EMEP_Bemerkung { get; set; }
        public double EMEP_NGF { get; set; }
        public double EMEP_EBF { get; set; }
        public int EMEP_AP { get; set; }
    }
}
