//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeedEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_FMS_Configuration
    {
        public string FC_Key { get; set; }
        public string FC_Value { get; set; }
        public string FC_Type { get; set; }
        public string FC_Remark { get; set; }
        public System.DateTime FC_LastModified { get; set; }
    }
}
