//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeedEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OR_Ref_Assets
    {
        public System.Guid ORA_UID { get; set; }
        public System.Guid ORA_Asset_Type_UID { get; set; }
        public System.Guid ORA_Asset_UID { get; set; }
        public System.Guid ORA_Object_UID { get; set; }
        public System.DateTime ORA_Created { get; set; }
        public int ORA_Status { get; set; }
    }
}
