//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeedEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_REM_Ref_Tagesplan
    {
        public System.Guid REMTP_UID { get; set; }
        public string REMTP_Code { get; set; }
        public string REMTP_Kurz_de { get; set; }
        public string REMTP_Kurz_fr { get; set; }
        public string REMTP_Kurz_it { get; set; }
        public string REMTP_Kurz_en { get; set; }
        public string REMTP_Lang_de { get; set; }
        public string REMTP_Lang_fr { get; set; }
        public string REMTP_Lang_it { get; set; }
        public string REMTP_Lang_en { get; set; }
        public int REMTP_Status { get; set; }
        public int REMTP_Sort { get; set; }
        public bool REMTP_IsDefault { get; set; }
        public Nullable<int> REMTP_StylizerBack { get; set; }
        public Nullable<int> REMTP_StylizerFore { get; set; }
        public Nullable<int> REMTP_StylizerPattern { get; set; }
        public Nullable<int> REMTP_StylizerLine { get; set; }
    
        public virtual T_SYS_ApertureColorToHex T_SYS_ApertureColorToHex { get; set; }
    }
}
