//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeedEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SessionValues
    {
        public System.Guid Key_UID { get; set; }
        public Nullable<int> Key_Tracking_ID { get; set; }
        public string Key_Method { get; set; }
        public string Key_Session_ID { get; set; }
        public string Key_Name { get; set; }
        public string Key_DataType { get; set; }
        public string Key_Value { get; set; }
    }
}
