//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeedEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SYS_Ref_Register
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_SYS_Ref_Register()
        {
            this.T_SYS_Ref_Register1 = new HashSet<T_SYS_Ref_Register>();
            this.T_SYS_Registerrechte = new HashSet<T_SYS_Registerrechte>();
            this.T_ZO_OV_Ref_Objekttyp_T_SYS_Ref_Register = new HashSet<T_ZO_OV_Ref_Objekttyp_T_SYS_Ref_Register>();
        }
    
        public System.Guid REG_UID { get; set; }
        public Nullable<System.Guid> REG_REG_UID { get; set; }
        public Nullable<System.Guid> REG_MOD_UID { get; set; }
        public string REG_Code { get; set; }
        public string REG_LANG_DE { get; set; }
        public string REG_LANG_EN { get; set; }
        public string REG_LANG_FR { get; set; }
        public string REG_LANG_IT { get; set; }
        public string REG_Control { get; set; }
        public Nullable<bool> REG_Show { get; set; }
        public int REG_Status { get; set; }
        public int REG_Sort { get; set; }
    
        public virtual T_SYS_Module T_SYS_Module { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_SYS_Ref_Register> T_SYS_Ref_Register1 { get; set; }
        public virtual T_SYS_Ref_Register T_SYS_Ref_Register2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_SYS_Registerrechte> T_SYS_Registerrechte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ZO_OV_Ref_Objekttyp_T_SYS_Ref_Register> T_ZO_OV_Ref_Objekttyp_T_SYS_Ref_Register { get; set; }
    }
}
