//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeedEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SYS_Ref_Tage
    {
        public System.Guid TAG_UID { get; set; }
        public int TAG_MDT_ID { get; set; }
        public Nullable<int> TAG_Code { get; set; }
        public string TAG_Kurz_DE { get; set; }
        public string TAG_Kurz_FR { get; set; }
        public string TAG_Kurz_IT { get; set; }
        public string TAG_Kurz_EN { get; set; }
        public string TAG_Lang_DE { get; set; }
        public string TAG_Lang_FR { get; set; }
        public string TAG_Lang_IT { get; set; }
        public string TAG_Lang_EN { get; set; }
        public int TAG_Status { get; set; }
        public int TAG_Sort { get; set; }
        public Nullable<int> TAG_StylizerFore { get; set; }
        public Nullable<int> TAG_StylizerBack { get; set; }
        public Nullable<int> TAG_StylizerPattern { get; set; }
        public Nullable<int> TAG_StylizerLine { get; set; }
        public bool TAG_IsDefault { get; set; }
        public Nullable<System.DateTime> TAG_DatumMut { get; set; }
        public string TAG_DatumUser { get; set; }
    
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
        public virtual T_SYS_ApertureColorToHex T_SYS_ApertureColorToHex { get; set; }
    }
}
