//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeedEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SYS_Grundstueckrechte
    {
        public System.Guid GRUR_UID { get; set; }
        public int GRUR_MDT_ID { get; set; }
        public int GRUR_GRANTEE_ID { get; set; }
        public Nullable<System.Guid> GRUR_GRU_UID { get; set; }
        public bool GRUR_IsRead { get; set; }
        public bool GRUR_IsWrite { get; set; }
        public bool GRUR_IsInsert { get; set; }
        public bool GRUR_IsDelete { get; set; }
        public int GRUR_Status { get; set; }
    
        public virtual T_AP_Grundstueck T_AP_Grundstueck { get; set; }
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
        public virtual T_Benutzergruppen T_Benutzergruppen { get; set; }
    }
}
