//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeedEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SYS_Ref_Language
    {
        public System.Guid LANG_UID { get; set; }
        public int LANG_MDT_ID { get; set; }
        public Nullable<int> LANG_Code { get; set; }
        public string LANG_Kurz_DE { get; set; }
        public string LANG_Kurz_FR { get; set; }
        public string LANG_Kurz_IT { get; set; }
        public string LANG_Kurz_EN { get; set; }
        public string LANG_Lang_DE { get; set; }
        public string LANG_Lang_FR { get; set; }
        public string LANG_Lang_IT { get; set; }
        public string LANG_Lang_EN { get; set; }
        public int LANG_Status { get; set; }
        public int LANG_Sort { get; set; }
        public Nullable<int> LANG_StylizerFore { get; set; }
        public Nullable<int> LANG_StylizerBack { get; set; }
        public Nullable<int> LANG_StylizerPattern { get; set; }
        public Nullable<int> LANG_StylizerLine { get; set; }
        public bool LANG_IsDefault { get; set; }
        public Nullable<System.DateTime> LANG_DatumMut { get; set; }
        public string LANG_DatumUser { get; set; }
    
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
        public virtual T_SYS_ApertureColorToHex T_SYS_ApertureColorToHex { get; set; }
    }
}
