//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeedEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SYS_Reportrechte
    {
        public System.Guid RER_UID { get; set; }
        public int RER_GRANTEE_ID { get; set; }
        public string RER_GRANTEE { get; set; }
        public Nullable<System.Guid> RER_RE_UID { get; set; }
        public bool RER_IsRead { get; set; }
        public int RER_Status { get; set; }
        public int RER_MDT_ID { get; set; }
    
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
    }
}
