//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeedEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TM_Ref_Checkliste
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_TM_Ref_Checkliste()
        {
            this.T_TM_Ref_Checkliste_Absatz = new HashSet<T_TM_Ref_Checkliste_Absatz>();
            this.T_TM_Ref_Checkliste_Checkpoints = new HashSet<T_TM_Ref_Checkliste_Checkpoints>();
            this.T_TM_Ref_Checkliste_Details = new HashSet<T_TM_Ref_Checkliste_Details>();
            this.T_TM_Ref_Checkliste_Taetigkeit = new HashSet<T_TM_Ref_Checkliste_Taetigkeit>();
            this.T_TM_Ref_Checkliste_Wartung = new HashSet<T_TM_Ref_Checkliste_Wartung>();
            this.T_TM_Tasks_Planung = new HashSet<T_TM_Tasks_Planung>();
            this.T_TM_Tasks = new HashSet<T_TM_Tasks>();
            this.T_ZO_OV_Ref_Objekttyp_TM_Ref_Checkliste = new HashSet<T_ZO_OV_Ref_Objekttyp_TM_Ref_Checkliste>();
            this.T_ZO_TASK_Ref_Checkliste_Comment = new HashSet<T_ZO_TASK_Ref_Checkliste_Comment>();
        }
    
        public System.Guid TCL_UID { get; set; }
        public int TCL_MDT_ID { get; set; }
        public Nullable<int> TCL_Code { get; set; }
        public string TCL_Kurz_DE { get; set; }
        public string TCL_Kurz_FR { get; set; }
        public string TCL_Kurz_IT { get; set; }
        public string TCL_Kurz_EN { get; set; }
        public string TCL_Lang_DE { get; set; }
        public string TCL_Lang_FR { get; set; }
        public string TCL_Lang_IT { get; set; }
        public string TCL_Lang_EN { get; set; }
        public int TCL_Status { get; set; }
        public int TCL_Sort { get; set; }
        public Nullable<int> TCL_StylizerFore { get; set; }
        public Nullable<int> TCL_StylizerBack { get; set; }
        public Nullable<int> TCL_StylizerPattern { get; set; }
        public Nullable<int> TCL_StylizerLine { get; set; }
        public bool TCL_IsDefault { get; set; }
        public Nullable<System.DateTime> TCL_DatumMut { get; set; }
        public string TCL_DatumUser { get; set; }
        public Nullable<System.Guid> TCL_TART_UID { get; set; }
        public Nullable<bool> TCL_showMaintenance { get; set; }
        public Nullable<bool> TCL_showJob { get; set; }
        public Nullable<bool> TCL_showNumber { get; set; }
        public Nullable<bool> TCL_isNew { get; set; }
        public Nullable<System.Guid> TCL_TKAT_UID { get; set; }
    
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
        public virtual T_SYS_ApertureColorToHex T_SYS_ApertureColorToHex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_TM_Ref_Checkliste_Absatz> T_TM_Ref_Checkliste_Absatz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_TM_Ref_Checkliste_Checkpoints> T_TM_Ref_Checkliste_Checkpoints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_TM_Ref_Checkliste_Details> T_TM_Ref_Checkliste_Details { get; set; }
        public virtual T_TM_Ref_TaskArt T_TM_Ref_TaskArt { get; set; }
        public virtual T_TM_Ref_TaskKategorie T_TM_Ref_TaskKategorie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_TM_Ref_Checkliste_Taetigkeit> T_TM_Ref_Checkliste_Taetigkeit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_TM_Ref_Checkliste_Wartung> T_TM_Ref_Checkliste_Wartung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_TM_Tasks_Planung> T_TM_Tasks_Planung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_TM_Tasks> T_TM_Tasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ZO_OV_Ref_Objekttyp_TM_Ref_Checkliste> T_ZO_OV_Ref_Objekttyp_TM_Ref_Checkliste { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ZO_TASK_Ref_Checkliste_Comment> T_ZO_TASK_Ref_Checkliste_Comment { get; set; }
    }
}
