//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeedEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TM_Ref_TaskStatus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_TM_Ref_TaskStatus()
        {
            this.T_TM_Tasks = new HashSet<T_TM_Tasks>();
            this.T_ZO_TM_TSTA_TSK = new HashSet<T_ZO_TM_TSTA_TSK>();
        }
    
        public System.Guid TSTA_UID { get; set; }
        public int TSTA_MDT_ID { get; set; }
        public Nullable<int> TSTA_Code { get; set; }
        public string TSTA_Kurz_DE { get; set; }
        public string TSTA_Kurz_FR { get; set; }
        public string TSTA_Kurz_IT { get; set; }
        public string TSTA_Kurz_EN { get; set; }
        public string TSTA_Lang_DE { get; set; }
        public string TSTA_Lang_FR { get; set; }
        public string TSTA_Lang_IT { get; set; }
        public string TSTA_Lang_EN { get; set; }
        public int TSTA_Status { get; set; }
        public int TSTA_Sort { get; set; }
        public Nullable<int> TSTA_StylizerFore { get; set; }
        public Nullable<int> TSTA_StylizerBack { get; set; }
        public Nullable<int> TSTA_StylizerPattern { get; set; }
        public Nullable<int> TSTA_StylizerLine { get; set; }
        public bool TSTA_IsDefault { get; set; }
        public Nullable<System.DateTime> TSTA_DatumMut { get; set; }
        public string TSTA_DatumUser { get; set; }
        public bool TSTA_IsStoerung { get; set; }
        public Nullable<bool> TSTA_IsDone { get; set; }
    
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
        public virtual T_SYS_ApertureColorToHex T_SYS_ApertureColorToHex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_TM_Tasks> T_TM_Tasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ZO_TM_TSTA_TSK> T_ZO_TM_TSTA_TSK { get; set; }
    }
}
