//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeedEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ZO_AP_Aussenobjekt_AP_Ref_Anmietvertraege
    {
        public System.Guid ZO_AOANVTR_UID { get; set; }
        public System.Guid ZO_AOANVTR_AO_UID { get; set; }
        public System.Guid ZO_AOANVTR_VTR_UID { get; set; }
        public System.DateTime ZO_AOANVTR_DatumVon { get; set; }
        public System.DateTime ZO_AOANVTR_DatumBis { get; set; }
        public int ZO_AOANVTR_Status { get; set; }
        public double ZO_AOANVTR_PreisM2 { get; set; }
        public double ZO_AOANVTR_Flaeche { get; set; }
        public double ZO_AOANVTR_PreisStueck { get; set; }
        public double ZO_AOANVTR_AnzObjekte { get; set; }
        public string ZO_AOANVTR_Bemerkung { get; set; }
        public Nullable<double> ZO_AOANVTR_FlaecheProzent { get; set; }
    
        public virtual T_AP_Aussenobjekt T_AP_Aussenobjekt { get; set; }
        public virtual T_VM_Vertraege T_VM_Vertraege { get; set; }
    }
}
