//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeedEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ZO_REM_AP_Raum_Ausstattung
    {
        public System.Guid ZO_RMAS_UID { get; set; }
        public System.Guid ZO_RMAS_RM_UID { get; set; }
        public Nullable<System.Guid> ZO_RMAS_REMRN_UID { get; set; }
        public Nullable<System.Guid> ZO_RMAS_REMBB_UID { get; set; }
        public System.DateTime ZO_RMAS_GueltigVon { get; set; }
        public System.DateTime ZO_RMAS_GueltigBis { get; set; }
        public int ZO_RMAS_Status { get; set; }
    
        public virtual T_AP_Raum T_AP_Raum { get; set; }
        public virtual T_REM_Ref_Bodenbelag T_REM_Ref_Bodenbelag { get; set; }
        public virtual T_REM_Ref_RaumName T_REM_Ref_RaumName { get; set; }
    }
}
