//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeedEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ZO_AP_Parkplatz_AP_Kontakte
    {
        public System.Guid ZO_PPKT_UID { get; set; }
        public System.Guid ZO_PPKT_PP_UID { get; set; }
        public System.Guid ZO_PPKT_KT_UID { get; set; }
        public System.DateTime ZO_PPKT_DatumVon { get; set; }
        public System.DateTime ZO_PPKT_DatumBis { get; set; }
        public int ZO_PPKT_Status { get; set; }
        public double ZO_PPKT_PreisM2 { get; set; }
        public double ZO_PPKT_Flaeche { get; set; }
        public double ZO_PPKT_Mietansatz { get; set; }
        public string ZO_PPKT_Schild { get; set; }
        public string ZO_PPKT_Bemerkung { get; set; }
        public double ZO_PPKT_FlaecheProzent { get; set; }
    
        public virtual T_AP_Kontakte T_AP_Kontakte { get; set; }
        public virtual T_AP_Parkplatz T_AP_Parkplatz { get; set; }
    }
}
