//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeedEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ZO_TASK_Ref_Checkliste_Comment
    {
        public System.Guid ZO_TSKTCLCOMMENT_UID { get; set; }
        public Nullable<System.Guid> ZO_TSKTCLCOMMENT_TSK_UID { get; set; }
        public Nullable<System.Guid> ZO_TSKTCLCOMMENT_TCL_UID { get; set; }
        public string ZO_TSKTCLCOMMENT_Comment { get; set; }
        public Nullable<System.Guid> ZO_TSKTCLCOMMENT_TPL_UID { get; set; }
        public int ZO_TSKTCLCOMMENT_Status { get; set; }
    
        public virtual T_TM_Ref_Checkliste T_TM_Ref_Checkliste { get; set; }
        public virtual T_TM_Tasks T_TM_Tasks { get; set; }
        public virtual T_TM_Tasks_Planung T_TM_Tasks_Planung { get; set; }
    }
}
