//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeedEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ZO_AP_Gebaeude_DWG
    {
        public System.Guid ZO_GBDWG_UID { get; set; }
        public System.Guid ZO_GBDWG_GB_UID { get; set; }
        public string ZO_GBDWG_ApertureDWG { get; set; }
        public System.DateTime ZO_GBDWG_DatumVon { get; set; }
        public System.DateTime ZO_GBDWG_DatumBis { get; set; }
        public string ZO_GBDWG_ApertureObjID { get; set; }
        public int ZO_GBDWG_Status { get; set; }
        public string ZO_GBDWG_DWGID { get; set; }
    
        public virtual T_AP_Gebaeude T_AP_Gebaeude { get; set; }
    }
}
