//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeedEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ZO_AP_Parkplatz_AP_Ref_Kostenstelle
    {
        public System.Guid ZO_PPKST_UID { get; set; }
        public System.Guid ZO_PPKST_PP_UID { get; set; }
        public System.Guid ZO_PPKST_KST_UID { get; set; }
        public System.DateTime ZO_PPKST_DatumVon { get; set; }
        public System.DateTime ZO_PPKST_DatumBis { get; set; }
        public int ZO_PPKST_Status { get; set; }
        public double ZO_PPKST_Preis { get; set; }
        public string ZO_PPKST_Bemerkung { get; set; }
        public Nullable<double> ZO_PPKST_FlaecheProz { get; set; }
    
        public virtual T_AP_Parkplatz T_AP_Parkplatz { get; set; }
        public virtual T_AP_Ref_Kostenstelle T_AP_Ref_Kostenstelle { get; set; }
    }
}
