//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeedEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ZO_T_AP_Standort_T_IGM_Ref_Leistungsart
    {
        public System.Guid ZORL_UID { get; set; }
        public Nullable<System.Guid> ZORL_LA_UID { get; set; }
        public Nullable<System.Guid> ZORL_SO_UID { get; set; }
        public string ZORL_Dienstleister { get; set; }
        public string ZORL_Auftraggeber { get; set; }
        public string ZORL_Beschreibung { get; set; }
        public string ZORL_Bemerkungen { get; set; }
        public Nullable<decimal> ZORL_AufwandIntern { get; set; }
        public Nullable<decimal> ZORL_AufwandExtern { get; set; }
        public Nullable<int> ZORL_Status { get; set; }
    
        public virtual T_AP_Standort T_AP_Standort { get; set; }
        public virtual T_IGM_Ref_Leistungsart T_IGM_Ref_Leistungsart { get; set; }
    }
}
