//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeedEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ZO_AP_Raum_AP_Ref_Mietobjekt
    {
        public System.Guid ZO_RMMIO_UID { get; set; }
        public System.Guid ZO_RMMIO_RM_UID { get; set; }
        public System.Guid ZO_RMMIO_MIO_UID { get; set; }
        public System.DateTime ZO_RMMIO_DatumVon { get; set; }
        public System.DateTime ZO_RMMIO_DatumBis { get; set; }
        public int ZO_RMMIO_Status { get; set; }
        public string ZO_RMMIO_Bemerkung { get; set; }
        public Nullable<double> ZO_RMMIO_Flaeche { get; set; }
        public Nullable<double> ZO_RMMIO_FlaecheProzent { get; set; }
    
        public virtual T_AP_Raum T_AP_Raum { get; set; }
        public virtual T_AP_Ref_Mietobjekt T_AP_Ref_Mietobjekt { get; set; }
    }
}
