//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeedEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ZO_AP_Schluesselgruppe_AP_Zylinder
    {
        public System.Guid ZO_SLGZYL_UID { get; set; }
        public System.Guid ZO_SLGZYL_SLG_UID { get; set; }
        public System.Guid ZO_SLGZYL_ZYL_UID { get; set; }
        public int ZO_SLGZYL_Status { get; set; }
    
        public virtual T_AP_Schluesselgruppe T_AP_Schluesselgruppe { get; set; }
        public virtual T_AP_Zylinder T_AP_Zylinder { get; set; }
    }
}
