//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_Ref_KunstAusleihart
    {
        public T_AP_Ref_KunstAusleihart()
        {
            this.T_ZO_AP_Kunst_Ausleihe = new HashSet<T_ZO_AP_Kunst_Ausleihe>();
        }
    
        public System.Guid KAART_UID { get; set; }
        public int KAART_MDT_ID { get; set; }
        public Nullable<int> KAART_Code { get; set; }
        public string KAART_Kurz_DE { get; set; }
        public string KAART_Kurz_FR { get; set; }
        public string KAART_Kurz_IT { get; set; }
        public string KAART_Kurz_EN { get; set; }
        public string KAART_Lang_DE { get; set; }
        public string KAART_Lang_FR { get; set; }
        public string KAART_Lang_IT { get; set; }
        public string KAART_Lang_EN { get; set; }
        public int KAART_Status { get; set; }
        public int KAART_Sort { get; set; }
        public Nullable<int> KAART_StylizerFore { get; set; }
        public Nullable<int> KAART_StylizerBack { get; set; }
        public Nullable<int> KAART_StylizerPattern { get; set; }
        public Nullable<int> KAART_StylizerLine { get; set; }
        public bool KAART_IsDefault { get; set; }
        public Nullable<System.DateTime> KAART_DatumMut { get; set; }
        public string KAART_DatumUser { get; set; }
    
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
        public virtual T_SYS_ApertureColorToHex T_SYS_ApertureColorToHex { get; set; }
        public virtual ICollection<T_ZO_AP_Kunst_Ausleihe> T_ZO_AP_Kunst_Ausleihe { get; set; }
    }
}
