//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_Kunst_Ref_Technik
    {
        public T_AP_Kunst_Ref_Technik()
        {
            this.T_AP_Kunst = new HashSet<T_AP_Kunst>();
        }
    
        public System.Guid KTEC_UID { get; set; }
        public int KTEC_MDT_ID { get; set; }
        public string KTEC_Code { get; set; }
        public string KTEC_Kurz_DE { get; set; }
        public string KTEC_Kurz_FR { get; set; }
        public string KTEC_Kurz_IT { get; set; }
        public string KTEC_Kurz_EN { get; set; }
        public string KTEC_Lang_DE { get; set; }
        public string KTEC_Lang_FR { get; set; }
        public string KTEC_Lang_IT { get; set; }
        public string KTEC_Lang_EN { get; set; }
        public int KTEC_Status { get; set; }
        public int KTEC_Sort { get; set; }
        public Nullable<int> KTEC_StylizerFore { get; set; }
        public Nullable<int> KTEC_StylizerBack { get; set; }
        public Nullable<int> KTEC_StylizerPattern { get; set; }
        public Nullable<int> KTEC_StylizerLine { get; set; }
        public bool KTEC_IsDefault { get; set; }
        public Nullable<System.DateTime> KTEC_DatumMut { get; set; }
        public string KTEC_DatumUser { get; set; }
    
        public virtual ICollection<T_AP_Kunst> T_AP_Kunst { get; set; }
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
        public virtual T_SYS_ApertureColorToHex T_SYS_ApertureColorToHex { get; set; }
    }
}
