//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_Ref_Nutzungsart
    {
        public T_AP_Ref_Nutzungsart()
        {
            this.T_AP_Raum = new HashSet<T_AP_Raum>();
            this.T_AP_Raum1 = new HashSet<T_AP_Raum>();
            this.T_AP_Ref_Nutzungsart_Raiffeisen = new HashSet<T_AP_Ref_Nutzungsart_Raiffeisen>();
            this.T_REM_Ref_Vorlagen = new HashSet<T_REM_Ref_Vorlagen>();
            this.T_ZO_AP_Raum_AP_Ref_Nutzungsart = new HashSet<T_ZO_AP_Raum_AP_Ref_Nutzungsart>();
            this.T_ZO_IGM_Reinigungsfaktor = new HashSet<T_ZO_IGM_Reinigungsfaktor>();
            this.T_ZO_REM_AP_Raum_Raumgruppe = new HashSet<T_ZO_REM_AP_Raum_Raumgruppe>();
        }
    
        public System.Guid NA_UID { get; set; }
        public string NA_Code { get; set; }
        public string NA_Kurz_DE { get; set; }
        public string NA_Kurz_FR { get; set; }
        public string NA_Kurz_IT { get; set; }
        public string NA_Kurz_EN { get; set; }
        public string NA_Lang_DE { get; set; }
        public string NA_Lang_FR { get; set; }
        public string NA_Lang_IT { get; set; }
        public string NA_Lang_EN { get; set; }
        public int NA_Status { get; set; }
        public int NA_Sort { get; set; }
        public Nullable<int> NA_StylizerBack { get; set; }
        public Nullable<int> NA_StylizerPattern { get; set; }
        public Nullable<int> NA_StylizerLine { get; set; }
        public bool NA_IsDefault { get; set; }
        public Nullable<System.DateTime> NA_DatumMut { get; set; }
        public string NA_DatumUser { get; set; }
        public bool NA_IsEBF { get; set; }
        public Nullable<System.Guid> NA_DIN277_UID { get; set; }
        public bool NA_IsVermietbar { get; set; }
        public Nullable<bool> NA_canBook { get; set; }
        public string NA_Bemerkung { get; set; }
        public bool NA_IsNetto { get; set; }
        public Nullable<decimal> NA_UmrechnungsFaktor { get; set; }
    
        public virtual ICollection<T_AP_Raum> T_AP_Raum { get; set; }
        public virtual ICollection<T_AP_Raum> T_AP_Raum1 { get; set; }
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
        public virtual ICollection<T_AP_Ref_Nutzungsart_Raiffeisen> T_AP_Ref_Nutzungsart_Raiffeisen { get; set; }
        public virtual T_AP_Ref_NutzungsartGruppe T_AP_Ref_NutzungsartGruppe { get; set; }
        public virtual T_SYS_ApertureColorToHex T_SYS_ApertureColorToHex { get; set; }
        public virtual ICollection<T_REM_Ref_Vorlagen> T_REM_Ref_Vorlagen { get; set; }
        public virtual ICollection<T_ZO_AP_Raum_AP_Ref_Nutzungsart> T_ZO_AP_Raum_AP_Ref_Nutzungsart { get; set; }
        public virtual ICollection<T_ZO_IGM_Reinigungsfaktor> T_ZO_IGM_Reinigungsfaktor { get; set; }
        public virtual ICollection<T_ZO_REM_AP_Raum_Raumgruppe> T_ZO_REM_AP_Raum_Raumgruppe { get; set; }
    }
}
