//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_Ref_Haus
    {
        public T_AP_Ref_Haus()
        {
            this.T_AP_Aussenobjekt = new HashSet<T_AP_Aussenobjekt>();
            this.T_AP_Parkplatz = new HashSet<T_AP_Parkplatz>();
            this.T_AP_Raum = new HashSet<T_AP_Raum>();
        }
    
        public System.Guid HS_UID { get; set; }
        public Nullable<int> HS_Code { get; set; }
        public string HS_Kurz_DE { get; set; }
        public string HS_Kurz_FR { get; set; }
        public string HS_Kurz_IT { get; set; }
        public string HS_Kurz_EN { get; set; }
        public string HS_Lang_DE { get; set; }
        public string HS_Lang_FR { get; set; }
        public string HS_Lang_IT { get; set; }
        public string HS_Lang_EN { get; set; }
        public int HS_Status { get; set; }
        public int HS_Sort { get; set; }
        public Nullable<int> HS_StylizerBack { get; set; }
        public Nullable<int> HS_StylizerPattern { get; set; }
        public Nullable<int> HS_StylizerLine { get; set; }
        public bool HS_IsDefault { get; set; }
        public Nullable<System.DateTime> HS_DatumMut { get; set; }
        public string HS_DatumUser { get; set; }
        public string HS_SO_Nr { get; set; }
    
        public virtual ICollection<T_AP_Aussenobjekt> T_AP_Aussenobjekt { get; set; }
        public virtual ICollection<T_AP_Parkplatz> T_AP_Parkplatz { get; set; }
        public virtual ICollection<T_AP_Raum> T_AP_Raum { get; set; }
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
        public virtual T_SYS_ApertureColorToHex T_SYS_ApertureColorToHex { get; set; }
    }
}
