//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_Ref_FotoKategorie
    {
        public T_AP_Ref_FotoKategorie()
        {
            this.T_AP_Fotos = new HashSet<T_AP_Fotos>();
        }
    
        public System.Guid FKAT_UID { get; set; }
        public Nullable<int> FKAT_Code { get; set; }
        public string FKAT_Kurz_DE { get; set; }
        public string FKAT_Kurz_FR { get; set; }
        public string FKAT_Kurz_IT { get; set; }
        public string FKAT_Kurz_EN { get; set; }
        public string FKAT_Lang_DE { get; set; }
        public string FKAT_Lang_FR { get; set; }
        public string FKAT_Lang_IT { get; set; }
        public string FKAT_Lang_EN { get; set; }
        public int FKAT_Status { get; set; }
        public int FKAT_Sort { get; set; }
        public Nullable<int> FKAT_StylizerBack { get; set; }
        public Nullable<int> FKAT_StylizerPattern { get; set; }
        public Nullable<int> FKAT_StylizerLine { get; set; }
        public bool FKAT_IsDefault { get; set; }
        public Nullable<System.DateTime> FKAT_DatumMut { get; set; }
        public string FKAT_DatumUser { get; set; }
    
        public virtual ICollection<T_AP_Fotos> T_AP_Fotos { get; set; }
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
        public virtual T_SYS_ApertureColorToHex T_SYS_ApertureColorToHex { get; set; }
    }
}
