//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_Ref_AussenobjektKategorie
    {
        public T_AP_Ref_AussenobjektKategorie()
        {
            this.T_AP_Aussenobjekt = new HashSet<T_AP_Aussenobjekt>();
        }
    
        public System.Guid AOKAT_UID { get; set; }
        public int AOKAT_MDT_ID { get; set; }
        public Nullable<int> AOKAT_Code { get; set; }
        public string AOKAT_Kurz_DE { get; set; }
        public string AOKAT_Kurz_FR { get; set; }
        public string AOKAT_Kurz_IT { get; set; }
        public string AOKAT_Kurz_EN { get; set; }
        public string AOKAT_Lang_DE { get; set; }
        public string AOKAT_Lang_FR { get; set; }
        public string AOKAT_Lang_IT { get; set; }
        public string AOKAT_Lang_EN { get; set; }
        public int AOKAT_Status { get; set; }
        public int AOKAT_Sort { get; set; }
        public Nullable<int> AOKAT_StylizerFore { get; set; }
        public Nullable<int> AOKAT_StylizerBack { get; set; }
        public Nullable<int> AOKAT_StylizerPattern { get; set; }
        public Nullable<int> AOKAT_StylizerLine { get; set; }
        public bool AOKAT_IsDefault { get; set; }
        public Nullable<System.DateTime> AOKAT_DatumMut { get; set; }
        public string AOKAT_DatumUser { get; set; }
    
        public virtual ICollection<T_AP_Aussenobjekt> T_AP_Aussenobjekt { get; set; }
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
        public virtual T_SYS_ApertureColorToHex T_SYS_ApertureColorToHex { get; set; }
    }
}
