//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_Grundstueck_History
    {
        public System.Guid HIGRU_UID { get; set; }
        public System.Guid HIGRU_Entry_UID { get; set; }
        public System.DateTime HIGRU_Datum { get; set; }
        public string HIGRU_User { get; set; }
        public string HIGRU_Feld_DE { get; set; }
        public string HIGRU_Feld_FR { get; set; }
        public string HIGRU_Feld_IT { get; set; }
        public string HIGRU_Feld_EN { get; set; }
        public string HIGRU_Alt_DE { get; set; }
        public string HIGRU_Alt_FR { get; set; }
        public string HIGRU_Alt_IT { get; set; }
        public string HIGRU_Alt_EN { get; set; }
        public string HIGRU_Neu_DE { get; set; }
        public string HIGRU_Neu_FR { get; set; }
        public string HIGRU_Neu_IT { get; set; }
        public string HIGRU_Neu_EN { get; set; }
        public bool HIGRU_IsNew { get; set; }
        public bool HIGRU_IsChange { get; set; }
        public bool HIGRU_IsUpload { get; set; }
        public bool HIGRU_IsDownload { get; set; }
        public bool HIGRU_IsClient { get; set; }
        public int HIGRU_Version { get; set; }
        public bool HIGRU_IsGeloescht { get; set; }
        public int HIGRU_Status { get; set; }
        public string HIGRU_Filter1 { get; set; }
        public string HIGRU_Filter2 { get; set; }
        public bool HIGRU_IsAction { get; set; }
        public bool HIGRU_IsSubEntry { get; set; }
    
        public virtual T_AP_Grundstueck T_AP_Grundstueck { get; set; }
    }
}
