//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_Arbeitsplatz
    {
        public T_AP_Arbeitsplatz()
        {
            this.T_AP_Arbeitsplatz_History = new HashSet<T_AP_Arbeitsplatz_History>();
            this.T_AP_Informatik = new HashSet<T_AP_Informatik>();
            this.T_AP_Kommunikation = new HashSet<T_AP_Kommunikation>();
            this.T_AP_Mobiliar = new HashSet<T_AP_Mobiliar>();
            this.T_MM_Umzug_Bestand = new HashSet<T_MM_Umzug_Bestand>();
            this.T_MM_Umzug_Bestand1 = new HashSet<T_MM_Umzug_Bestand>();
            this.T_MM_Umzug = new HashSet<T_MM_Umzug>();
            this.T_MM_Umzug1 = new HashSet<T_MM_Umzug>();
            this.T_SYS_Arbeitsplatzrechte = new HashSet<T_SYS_Arbeitsplatzrechte>();
            this.T_TM_Tasks_Planung = new HashSet<T_TM_Tasks_Planung>();
            this.T_TM_Tasks = new HashSet<T_TM_Tasks>();
            this.T_UM_Umzug = new HashSet<T_UM_Umzug>();
            this.T_ZO_AP_Arbeitsplatz_AP_Belegung = new HashSet<T_ZO_AP_Arbeitsplatz_AP_Belegung>();
            this.T_ZO_AP_Arbeitsplatz_AP_Ref_Kostenstelle = new HashSet<T_ZO_AP_Arbeitsplatz_AP_Ref_Kostenstelle>();
            this.T_ZO_AP_Arbeitsplatz_AP_Ref_Organisationseinheit = new HashSet<T_ZO_AP_Arbeitsplatz_AP_Ref_Organisationseinheit>();
            this.T_ZO_AP_Arbeitsplatz_DWG = new HashSet<T_ZO_AP_Arbeitsplatz_DWG>();
            this.T_ZO_AP_Arbeitsplatz_Reservation = new HashSet<T_ZO_AP_Arbeitsplatz_Reservation>();
        }
    
        public System.Guid AP_UID { get; set; }
        public int AP_MDT_ID { get; set; }
        public Nullable<System.Guid> AP_RM_UID { get; set; }
        public Nullable<System.Guid> AP_APK_UID { get; set; }
        public string AP_ApertureKey { get; set; }
        public string AP_Nr { get; set; }
        public string AP_Bezeichnung { get; set; }
        public string AP_Bemerkung { get; set; }
        public System.DateTime AP_DatumVon { get; set; }
        public System.DateTime AP_DatumBis { get; set; }
        public int AP_Status { get; set; }
        public Nullable<bool> AP_IsKrisenarbeitsplatz { get; set; }
        public Nullable<bool> AP_canBook { get; set; }
        public Nullable<decimal> AP_Price { get; set; }
    
        public virtual ICollection<T_AP_Arbeitsplatz_History> T_AP_Arbeitsplatz_History { get; set; }
        public virtual T_AP_Raum T_AP_Raum { get; set; }
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
        public virtual ICollection<T_AP_Informatik> T_AP_Informatik { get; set; }
        public virtual ICollection<T_AP_Kommunikation> T_AP_Kommunikation { get; set; }
        public virtual ICollection<T_AP_Mobiliar> T_AP_Mobiliar { get; set; }
        public virtual ICollection<T_MM_Umzug_Bestand> T_MM_Umzug_Bestand { get; set; }
        public virtual ICollection<T_MM_Umzug_Bestand> T_MM_Umzug_Bestand1 { get; set; }
        public virtual ICollection<T_MM_Umzug> T_MM_Umzug { get; set; }
        public virtual ICollection<T_MM_Umzug> T_MM_Umzug1 { get; set; }
        public virtual ICollection<T_SYS_Arbeitsplatzrechte> T_SYS_Arbeitsplatzrechte { get; set; }
        public virtual ICollection<T_TM_Tasks_Planung> T_TM_Tasks_Planung { get; set; }
        public virtual ICollection<T_TM_Tasks> T_TM_Tasks { get; set; }
        public virtual ICollection<T_UM_Umzug> T_UM_Umzug { get; set; }
        public virtual ICollection<T_ZO_AP_Arbeitsplatz_AP_Belegung> T_ZO_AP_Arbeitsplatz_AP_Belegung { get; set; }
        public virtual ICollection<T_ZO_AP_Arbeitsplatz_AP_Ref_Kostenstelle> T_ZO_AP_Arbeitsplatz_AP_Ref_Kostenstelle { get; set; }
        public virtual ICollection<T_ZO_AP_Arbeitsplatz_AP_Ref_Organisationseinheit> T_ZO_AP_Arbeitsplatz_AP_Ref_Organisationseinheit { get; set; }
        public virtual ICollection<T_ZO_AP_Arbeitsplatz_DWG> T_ZO_AP_Arbeitsplatz_DWG { get; set; }
        public virtual ICollection<T_ZO_AP_Arbeitsplatz_Reservation> T_ZO_AP_Arbeitsplatz_Reservation { get; set; }
    }
}
