//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_Dose
    {
        public T_AP_Dose()
        {
            this.T_AP_Anschluss = new HashSet<T_AP_Anschluss>();
            this.T_AP_Dose_History = new HashSet<T_AP_Dose_History>();
            this.T_TM_Tasks_Planung = new HashSet<T_TM_Tasks_Planung>();
            this.T_TM_Tasks = new HashSet<T_TM_Tasks>();
            this.T_ZO_AP_Dose_DWG = new HashSet<T_ZO_AP_Dose_DWG>();
        }
    
        public System.Guid DO_UID { get; set; }
        public int DO_MDT_ID { get; set; }
        public Nullable<System.Guid> DO_RM_UID { get; set; }
        public Nullable<System.Guid> DO_DKAT_UID { get; set; }
        public string DO_ApertureKey { get; set; }
        public string DO_Nr { get; set; }
        public string DO_Bezeichnung { get; set; }
        public string DO_Bemerkung { get; set; }
        public System.DateTime DO_DatumVon { get; set; }
        public System.DateTime DO_DatumBis { get; set; }
        public int DO_Status { get; set; }
    
        public virtual ICollection<T_AP_Anschluss> T_AP_Anschluss { get; set; }
        public virtual ICollection<T_AP_Dose_History> T_AP_Dose_History { get; set; }
        public virtual T_AP_Raum T_AP_Raum { get; set; }
        public virtual T_AP_Ref_DoseKategorie T_AP_Ref_DoseKategorie { get; set; }
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
        public virtual ICollection<T_TM_Tasks_Planung> T_TM_Tasks_Planung { get; set; }
        public virtual ICollection<T_TM_Tasks> T_TM_Tasks { get; set; }
        public virtual ICollection<T_ZO_AP_Dose_DWG> T_ZO_AP_Dose_DWG { get; set; }
    }
}
