//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_Zylinder
    {
        public T_AP_Zylinder()
        {
            this.T_AP_Zylinder_History = new HashSet<T_AP_Zylinder_History>();
            this.T_SYS_Zylinderrechte = new HashSet<T_SYS_Zylinderrechte>();
            this.T_TM_Tasks_Planung = new HashSet<T_TM_Tasks_Planung>();
            this.T_TM_Tasks = new HashSet<T_TM_Tasks>();
            this.T_ZO_AP_Schluesselgruppe_AP_Zylinder = new HashSet<T_ZO_AP_Schluesselgruppe_AP_Zylinder>();
            this.T_ZO_AP_Zylinder_AP_Schluesselgruppe_Benutzer = new HashSet<T_ZO_AP_Zylinder_AP_Schluesselgruppe_Benutzer>();
            this.T_ZO_AP_Zylinder_DWG = new HashSet<T_ZO_AP_Zylinder_DWG>();
            this.T_AP_Ref_Mandant1 = new HashSet<T_AP_Ref_Mandant>();
        }
    
        public System.Guid ZYL_UID { get; set; }
        public int ZYL_MDT_ID { get; set; }
        public string ZYL_ApertureKey { get; set; }
        public Nullable<System.Guid> ZYL_TR_UID { get; set; }
        public Nullable<System.Guid> ZYL_ZKAT_UID { get; set; }
        public Nullable<System.Guid> ZYL_ZYLT_UID { get; set; }
        public Nullable<System.Guid> ZYL_ZSYS_UID { get; set; }
        public string ZYL_Nr { get; set; }
        public string ZYL_Bezeichnung { get; set; }
        public string ZYL_Bemerkung { get; set; }
        public System.DateTime ZYL_DatumVon { get; set; }
        public System.DateTime ZYL_DatumBis { get; set; }
        public int ZYL_Status { get; set; }
        public Nullable<System.Guid> ZYL_RM_UID { get; set; }
        public Nullable<System.Guid> ZYL_MO_UID { get; set; }
        public Nullable<System.Guid> ZYL_SMDT_UID { get; set; }
        public Nullable<System.Guid> ZYL_SA_UID { get; set; }
        public string ZYL_Typ { get; set; }
        public Nullable<System.Guid> ZYL_ZSTA_UID { get; set; }
        public Nullable<System.Guid> ZYL_ZK_UID { get; set; }
    
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
        public virtual T_AP_Ref_SchliessungMandant T_AP_Ref_SchliessungMandant { get; set; }
        public virtual T_AP_Ref_ZylinderKasse T_AP_Ref_ZylinderKasse { get; set; }
        public virtual T_AP_Ref_ZylinderKategorie T_AP_Ref_ZylinderKategorie { get; set; }
        public virtual T_AP_Ref_ZylinderSchliesssystem T_AP_Ref_ZylinderSchliesssystem { get; set; }
        public virtual T_AP_Ref_ZylinderStatus T_AP_Ref_ZylinderStatus { get; set; }
        public virtual T_AP_Ref_ZylinderTyp T_AP_Ref_ZylinderTyp { get; set; }
        public virtual T_AP_Tuer T_AP_Tuer { get; set; }
        public virtual ICollection<T_AP_Zylinder_History> T_AP_Zylinder_History { get; set; }
        public virtual ICollection<T_SYS_Zylinderrechte> T_SYS_Zylinderrechte { get; set; }
        public virtual ICollection<T_TM_Tasks_Planung> T_TM_Tasks_Planung { get; set; }
        public virtual ICollection<T_TM_Tasks> T_TM_Tasks { get; set; }
        public virtual ICollection<T_ZO_AP_Schluesselgruppe_AP_Zylinder> T_ZO_AP_Schluesselgruppe_AP_Zylinder { get; set; }
        public virtual ICollection<T_ZO_AP_Zylinder_AP_Schluesselgruppe_Benutzer> T_ZO_AP_Zylinder_AP_Schluesselgruppe_Benutzer { get; set; }
        public virtual ICollection<T_ZO_AP_Zylinder_DWG> T_ZO_AP_Zylinder_DWG { get; set; }
        public virtual ICollection<T_AP_Ref_Mandant> T_AP_Ref_Mandant1 { get; set; }
    }
}
