//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_Ref_Energiebezugsart
    {
        public T_AP_Ref_Energiebezugsart()
        {
            this.T_ZO_AP_Raum_AP_Ref_Energiebezugsart = new HashSet<T_ZO_AP_Raum_AP_Ref_Energiebezugsart>();
        }
    
        public System.Guid EBA_UID { get; set; }
        public Nullable<int> EBA_Code { get; set; }
        public string EBA_Kurz_DE { get; set; }
        public string EBA_Kurz_FR { get; set; }
        public string EBA_Kurz_IT { get; set; }
        public string EBA_Kurz_EN { get; set; }
        public string EBA_Lang_DE { get; set; }
        public string EBA_Lang_FR { get; set; }
        public string EBA_Lang_IT { get; set; }
        public string EBA_Lang_EN { get; set; }
        public int EBA_Status { get; set; }
        public int EBA_Sort { get; set; }
        public Nullable<int> EBA_StylizerBack { get; set; }
        public Nullable<int> EBA_StylizerPattern { get; set; }
        public Nullable<int> EBA_StylizerLine { get; set; }
        public bool EBA_IsDefault { get; set; }
        public Nullable<System.DateTime> EBA_DatumMut { get; set; }
        public string EBA_DatumUser { get; set; }
    
        public virtual T_SYS_ApertureColorToHex T_SYS_ApertureColorToHex { get; set; }
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
        public virtual ICollection<T_ZO_AP_Raum_AP_Ref_Energiebezugsart> T_ZO_AP_Raum_AP_Ref_Energiebezugsart { get; set; }
    }
}
