//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_Ref_ZoneKategorie
    {
        public T_AP_Ref_ZoneKategorie()
        {
            this.T_AP_Zone = new HashSet<T_AP_Zone>();
        }
    
        public System.Guid ZKAT_UID { get; set; }
        public int ZKAT_MDT_ID { get; set; }
        public Nullable<int> ZKAT_Code { get; set; }
        public string ZKAT_Kurz_DE { get; set; }
        public string ZKAT_Kurz_FR { get; set; }
        public string ZKAT_Kurz_IT { get; set; }
        public string ZKAT_Kurz_EN { get; set; }
        public string ZKAT_Lang_DE { get; set; }
        public string ZKAT_Lang_FR { get; set; }
        public string ZKAT_Lang_IT { get; set; }
        public string ZKAT_Lang_EN { get; set; }
        public int ZKAT_Status { get; set; }
        public int ZKAT_Sort { get; set; }
        public Nullable<int> ZKAT_StylizerFore { get; set; }
        public Nullable<int> ZKAT_StylizerBack { get; set; }
        public Nullable<int> ZKAT_StylizerPattern { get; set; }
        public Nullable<int> ZKAT_StylizerLine { get; set; }
        public bool ZKAT_IsDefault { get; set; }
        public Nullable<System.DateTime> ZKAT_DatumMut { get; set; }
        public string ZKAT_DatumUser { get; set; }
    
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
        public virtual T_SYS_ApertureColorToHex T_SYS_ApertureColorToHex { get; set; }
        public virtual ICollection<T_AP_Zone> T_AP_Zone { get; set; }
    }
}
