//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_Ref_Zonenzuteilung
    {
        public T_AP_Ref_Zonenzuteilung()
        {
            this.T_AP_Gebaeude = new HashSet<T_AP_Gebaeude>();
        }
    
        public System.Guid ZZT_UID { get; set; }
        public int ZZT_MDT_ID { get; set; }
        public Nullable<int> ZZT_Code { get; set; }
        public string ZZT_Kurz_DE { get; set; }
        public string ZZT_Kurz_FR { get; set; }
        public string ZZT_Kurz_IT { get; set; }
        public string ZZT_Kurz_EN { get; set; }
        public string ZZT_Lang_DE { get; set; }
        public string ZZT_Lang_FR { get; set; }
        public string ZZT_Lang_IT { get; set; }
        public string ZZT_Lang_EN { get; set; }
        public int ZZT_Status { get; set; }
        public int ZZT_Sort { get; set; }
        public Nullable<int> ZZT_StylizerFore { get; set; }
        public Nullable<int> ZZT_StylizerBack { get; set; }
        public Nullable<int> ZZT_StylizerPattern { get; set; }
        public Nullable<int> ZZT_StylizerLine { get; set; }
        public bool ZZT_IsDefault { get; set; }
        public Nullable<System.DateTime> ZZT_DatumMut { get; set; }
        public string ZZT_DatumUser { get; set; }
    
        public virtual ICollection<T_AP_Gebaeude> T_AP_Gebaeude { get; set; }
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
    }
}
