//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_Ref_AnlageWRG
    {
        public System.Guid AWRG_UID { get; set; }
        public int AWRG_MDT_ID { get; set; }
        public Nullable<int> AWRG_Code { get; set; }
        public string AWRG_Kurz_DE { get; set; }
        public string AWRG_Kurz_FR { get; set; }
        public string AWRG_Kurz_IT { get; set; }
        public string AWRG_Kurz_EN { get; set; }
        public string AWRG_Lang_DE { get; set; }
        public string AWRG_Lang_FR { get; set; }
        public string AWRG_Lang_IT { get; set; }
        public string AWRG_Lang_EN { get; set; }
        public int AWRG_Status { get; set; }
        public int AWRG_Sort { get; set; }
        public Nullable<int> AWRG_StylizerFore { get; set; }
        public Nullable<int> AWRG_StylizerBack { get; set; }
        public Nullable<int> AWRG_StylizerPattern { get; set; }
        public Nullable<int> AWRG_StylizerLine { get; set; }
        public bool AWRG_IsDefault { get; set; }
        public Nullable<System.DateTime> AWRG_DatumMut { get; set; }
        public string AWRG_DatumUser { get; set; }
    
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
    }
}
