//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_Dose_History
    {
        public System.Guid HIDO_UID { get; set; }
        public System.Guid HIDO_Entry_UID { get; set; }
        public System.DateTime HIDO_Datum { get; set; }
        public string HIDO_User { get; set; }
        public string HIDO_Feld_DE { get; set; }
        public string HIDO_Feld_FR { get; set; }
        public string HIDO_Feld_IT { get; set; }
        public string HIDO_Feld_EN { get; set; }
        public string HIDO_Alt_DE { get; set; }
        public string HIDO_Alt_FR { get; set; }
        public string HIDO_Alt_IT { get; set; }
        public string HIDO_Alt_EN { get; set; }
        public string HIDO_Neu_DE { get; set; }
        public string HIDO_Neu_FR { get; set; }
        public string HIDO_Neu_IT { get; set; }
        public string HIDO_Neu_EN { get; set; }
        public bool HIDO_IsNew { get; set; }
        public bool HIDO_IsChange { get; set; }
        public bool HIDO_IsUpload { get; set; }
        public bool HIDO_IsDownload { get; set; }
        public bool HIDO_IsClient { get; set; }
        public int HIDO_Version { get; set; }
        public bool HIDO_IsGeloescht { get; set; }
        public int HIDO_Status { get; set; }
        public string HIDO_Filter1 { get; set; }
        public string HIDO_Filter2 { get; set; }
        public bool HIDO_IsAction { get; set; }
        public bool HIDO_IsSubEntry { get; set; }
    
        public virtual T_AP_Dose T_AP_Dose { get; set; }
    }
}
