//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_Anlage_History
    {
        public System.Guid HIAL_UID { get; set; }
        public System.Guid HIAL_AL_UID { get; set; }
        public System.Guid HIAL_Entry_UID { get; set; }
        public System.DateTime HIAL_Datum { get; set; }
        public string HIAL_User { get; set; }
        public string HIAL_Feld_DE { get; set; }
        public string HIAL_Feld_FR { get; set; }
        public string HIAL_Feld_IT { get; set; }
        public string HIAL_Feld_EN { get; set; }
        public string HIAL_Alt_DE { get; set; }
        public string HIAL_Alt_FR { get; set; }
        public string HIAL_Alt_IT { get; set; }
        public string HIAL_Alt_EN { get; set; }
        public string HIAL_Neu_DE { get; set; }
        public string HIAL_Neu_FR { get; set; }
        public string HIAL_Neu_IT { get; set; }
        public string HIAL_Neu_EN { get; set; }
        public bool HIAL_IsNew { get; set; }
        public bool HIAL_IsChange { get; set; }
        public bool HIAL_IsUpload { get; set; }
        public bool HIAL_IsDownload { get; set; }
        public bool HIAL_IsClient { get; set; }
        public int HIAL_Version { get; set; }
        public bool HIAL_IsGeloescht { get; set; }
        public int HIAL_Status { get; set; }
        public string HIAL_Filter1 { get; set; }
        public string HIAL_Filter2 { get; set; }
        public bool HIAL_IsAction { get; set; }
        public bool HIAL_IsSubEntry { get; set; }
    
        public virtual T_AP_Anlage T_AP_Anlage { get; set; }
    }
}
