//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_Ref_FahrzeugTyp
    {
        public T_AP_Ref_FahrzeugTyp()
        {
            this.T_AP_Fahrzeug = new HashSet<T_AP_Fahrzeug>();
        }
    
        public System.Guid FZTYP_UID { get; set; }
        public int FZTYP_MDT_ID { get; set; }
        public Nullable<int> FZTYP_Code { get; set; }
        public string FZTYP_Kurz_DE { get; set; }
        public string FZTYP_Kurz_FR { get; set; }
        public string FZTYP_Kurz_IT { get; set; }
        public string FZTYP_Kurz_EN { get; set; }
        public string FZTYP_Lang_DE { get; set; }
        public string FZTYP_Lang_FR { get; set; }
        public string FZTYP_Lang_IT { get; set; }
        public string FZTYP_Lang_EN { get; set; }
        public int FZTYP_Status { get; set; }
        public int FZTYP_Sort { get; set; }
        public Nullable<int> FZTYP_StylizerFore { get; set; }
        public Nullable<int> FZTYP_StylizerBack { get; set; }
        public Nullable<int> FZTYP_StylizerPattern { get; set; }
        public Nullable<int> FZTYP_StylizerLine { get; set; }
        public bool FZTYP_IsDefault { get; set; }
        public Nullable<System.DateTime> FZTYP_DatumMut { get; set; }
        public string FZTYP_DatumUser { get; set; }
    
        public virtual ICollection<T_AP_Fahrzeug> T_AP_Fahrzeug { get; set; }
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
        public virtual T_SYS_ApertureColorToHex T_SYS_ApertureColorToHex { get; set; }
    }
}
