//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_Ref_AussenobjektAnschlagkastenMaterial
    {
        public T_AP_Ref_AussenobjektAnschlagkastenMaterial()
        {
            this.T_AP_Aussenobjekt = new HashSet<T_AP_Aussenobjekt>();
        }
    
        public System.Guid AAKM_UID { get; set; }
        public int AAKM_MDT_ID { get; set; }
        public Nullable<int> AAKM_Code { get; set; }
        public string AAKM_Kurz_DE { get; set; }
        public string AAKM_Kurz_FR { get; set; }
        public string AAKM_Kurz_IT { get; set; }
        public string AAKM_Kurz_EN { get; set; }
        public string AAKM_Lang_DE { get; set; }
        public string AAKM_Lang_FR { get; set; }
        public string AAKM_Lang_IT { get; set; }
        public string AAKM_Lang_EN { get; set; }
        public int AAKM_Status { get; set; }
        public int AAKM_Sort { get; set; }
        public Nullable<int> AAKM_StylizerFore { get; set; }
        public Nullable<int> AAKM_StylizerBack { get; set; }
        public Nullable<int> AAKM_StylizerPattern { get; set; }
        public Nullable<int> AAKM_StylizerLine { get; set; }
        public bool AAKM_IsDefault { get; set; }
        public Nullable<System.DateTime> AAKM_DatumMut { get; set; }
        public string AAKM_DatumUser { get; set; }
    
        public virtual ICollection<T_AP_Aussenobjekt> T_AP_Aussenobjekt { get; set; }
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
    }
}
