//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_Tuer_History
    {
        public System.Guid HITR_UID { get; set; }
        public System.Guid HITR_Entry_UID { get; set; }
        public System.DateTime HITR_Datum { get; set; }
        public string HITR_User { get; set; }
        public string HITR_Feld_DE { get; set; }
        public string HITR_Feld_FR { get; set; }
        public string HITR_Feld_IT { get; set; }
        public string HITR_Feld_EN { get; set; }
        public string HITR_Alt_DE { get; set; }
        public string HITR_Alt_FR { get; set; }
        public string HITR_Alt_IT { get; set; }
        public string HITR_Alt_EN { get; set; }
        public string HITR_Neu_DE { get; set; }
        public string HITR_Neu_FR { get; set; }
        public string HITR_Neu_IT { get; set; }
        public string HITR_Neu_EN { get; set; }
        public bool HITR_IsNew { get; set; }
        public bool HITR_IsChange { get; set; }
        public bool HITR_IsUpload { get; set; }
        public bool HITR_IsDownload { get; set; }
        public bool HITR_IsClient { get; set; }
        public int HITR_Version { get; set; }
        public bool HITR_IsGeloescht { get; set; }
        public int HITR_Status { get; set; }
        public string HITR_Filter1 { get; set; }
        public string HITR_Filter2 { get; set; }
        public bool HITR_IsAction { get; set; }
        public bool HITR_IsSubEntry { get; set; }
    
        public virtual T_AP_Tuer T_AP_Tuer { get; set; }
    }
}
