//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_Ref_AussenobjektNutzungsart
    {
        public T_AP_Ref_AussenobjektNutzungsart()
        {
            this.T_AP_Aussenobjekt = new HashSet<T_AP_Aussenobjekt>();
        }
    
        public System.Guid NA_UID { get; set; }
        public int NA_MDT_ID { get; set; }
        public Nullable<int> NA_Code { get; set; }
        public string NA_Kurz_DE { get; set; }
        public string NA_Kurz_FR { get; set; }
        public string NA_Kurz_IT { get; set; }
        public string NA_Kurz_EN { get; set; }
        public string NA_Lang_DE { get; set; }
        public string NA_Lang_FR { get; set; }
        public string NA_Lang_IT { get; set; }
        public string NA_Lang_EN { get; set; }
        public int NA_Status { get; set; }
        public int NA_Sort { get; set; }
        public Nullable<int> NA_StylizerFore { get; set; }
        public Nullable<int> NA_StylizerBack { get; set; }
        public Nullable<int> NA_StylizerPattern { get; set; }
        public Nullable<int> NA_StylizerLine { get; set; }
        public bool NA_IsDefault { get; set; }
        public Nullable<System.DateTime> NA_DatumMut { get; set; }
        public string NA_DatumUser { get; set; }
    
        public virtual ICollection<T_AP_Aussenobjekt> T_AP_Aussenobjekt { get; set; }
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
    }
}
