//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_Geschoss_Reichle
    {
        public System.Guid GS_UID { get; set; }
        public System.Guid GS_GS_UID { get; set; }
        public Nullable<System.Guid> GS_GSR_UID { get; set; }
        public int GS_Status { get; set; }
    
        public virtual T_AP_Geschoss T_AP_Geschoss { get; set; }
        public virtual T_AP_Ref_Geschoss_Reichle T_AP_Ref_Geschoss_Reichle { get; set; }
    }
}
