//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_Ref_TuerFunktion
    {
        public T_AP_Ref_TuerFunktion()
        {
            this.T_AP_Tuer = new HashSet<T_AP_Tuer>();
        }
    
        public System.Guid TF_UID { get; set; }
        public Nullable<int> TF_Code { get; set; }
        public string TF_Kurz_DE { get; set; }
        public string TF_Kurz_FR { get; set; }
        public string TF_Kurz_IT { get; set; }
        public string TF_Kurz_EN { get; set; }
        public string TF_Lang_DE { get; set; }
        public string TF_Lang_FR { get; set; }
        public string TF_Lang_IT { get; set; }
        public string TF_Lang_EN { get; set; }
        public int TF_Status { get; set; }
        public int TF_Sort { get; set; }
        public Nullable<int> TF_StylizerBack { get; set; }
        public Nullable<int> TF_StylizerPattern { get; set; }
        public Nullable<int> TF_StylizerLine { get; set; }
        public bool TF_IsDefault { get; set; }
        public Nullable<System.DateTime> TF_DatumMut { get; set; }
        public string TF_DatumUser { get; set; }
    
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
        public virtual T_SYS_ApertureColorToHex T_SYS_ApertureColorToHex { get; set; }
        public virtual ICollection<T_AP_Tuer> T_AP_Tuer { get; set; }
    }
}
