//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_Ref_Schliessungstyp
    {
        public T_AP_Ref_Schliessungstyp()
        {
            this.T_ZO_AP_Tuer_Schliessung = new HashSet<T_ZO_AP_Tuer_Schliessung>();
        }
    
        public System.Guid ST_UID { get; set; }
        public string ST_Code { get; set; }
        public string ST_Kurz_DE { get; set; }
        public string ST_Kurz_FR { get; set; }
        public string ST_Kurz_IT { get; set; }
        public string ST_Kurz_EN { get; set; }
        public string ST_Lang_DE { get; set; }
        public string ST_Lang_FR { get; set; }
        public string ST_Lang_IT { get; set; }
        public string ST_Lang_EN { get; set; }
        public int ST_Status { get; set; }
        public int ST_Sort { get; set; }
        public Nullable<int> ST_StylizerBack { get; set; }
        public Nullable<int> ST_StylizerPattern { get; set; }
        public Nullable<int> ST_StylizerLine { get; set; }
        public bool ST_IsDefault { get; set; }
        public Nullable<System.DateTime> ST_DatumMut { get; set; }
        public string ST_DatumUser { get; set; }
    
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
        public virtual T_SYS_ApertureColorToHex T_SYS_ApertureColorToHex { get; set; }
        public virtual ICollection<T_ZO_AP_Tuer_Schliessung> T_ZO_AP_Tuer_Schliessung { get; set; }
    }
}
