//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_Gebaeude_Reichle
    {
        public System.Guid GB_UID { get; set; }
        public string GB_Hausnummer { get; set; }
        public string GB_Suffix { get; set; }
        public int GB_Status { get; set; }
    
        public virtual T_AP_Gebaeude T_AP_Gebaeude { get; set; }
        public virtual T_AP_Ref_Strasse_Reichle T_AP_Ref_Strasse_Reichle { get; set; }
    }
}
