//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_Standort
    {
        public T_AP_Standort()
        {
            this.T_AP_Anlage = new HashSet<T_AP_Anlage>();
            this.T_AP_Aussenobjekt = new HashSet<T_AP_Aussenobjekt>();
            this.T_AP_Gebaeude = new HashSet<T_AP_Gebaeude>();
            this.T_AP_Grundstueck = new HashSet<T_AP_Grundstueck>();
            this.T_AP_Parkplatz = new HashSet<T_AP_Parkplatz>();
            this.T_AP_Sicherheit = new HashSet<T_AP_Sicherheit>();
            this.T_AP_Standort_History = new HashSet<T_AP_Standort_History>();
            this.T_AP_Standort1 = new HashSet<T_AP_Standort>();
            this.T_REM_Ref_Vorlagen = new HashSet<T_REM_Ref_Vorlagen>();
            this.T_SYS_Gebaeuderechte = new HashSet<T_SYS_Gebaeuderechte>();
            this.T_SYS_Standortrechte = new HashSet<T_SYS_Standortrechte>();
            this.T_TM_Tasks_Planung = new HashSet<T_TM_Tasks_Planung>();
            this.T_TM_Tasks = new HashSet<T_TM_Tasks>();
            this.T_UM_Umzug = new HashSet<T_UM_Umzug>();
            this.T_ZO_AP_Standort_DWG = new HashSet<T_ZO_AP_Standort_DWG>();
            this.T_ZO_MM_Standort_ServiceAnbieter = new HashSet<T_ZO_MM_Standort_ServiceAnbieter>();
            this.T_ZO_REM_AP_Standort_Planung = new HashSet<T_ZO_REM_AP_Standort_Planung>();
        }
    
        public System.Guid SO_UID { get; set; }
        public int SO_MDT_ID { get; set; }
        public Nullable<System.Guid> SO_ORT_UID { get; set; }
        public string SO_ApertureKey { get; set; }
        public string SO_Nr { get; set; }
        public string SO_Bezeichnung { get; set; }
        public string SO_Bemerkung { get; set; }
        public System.DateTime SO_DatumVon { get; set; }
        public System.DateTime SO_DatumBis { get; set; }
        public int SO_Status { get; set; }
        public Nullable<System.DateTime> SO_MutDate { get; set; }
        public string SO_MutUser { get; set; }
        public bool SO_IsSchnittstelleWP { get; set; }
        public Nullable<System.Guid> SO_SO_UID { get; set; }
        public Nullable<decimal> SO_GM_Lat { get; set; }
        public Nullable<decimal> SO_GM_Lng { get; set; }
        public Nullable<System.Guid> SO_ADR_UID { get; set; }
    
        public virtual ICollection<T_AP_Anlage> T_AP_Anlage { get; set; }
        public virtual ICollection<T_AP_Aussenobjekt> T_AP_Aussenobjekt { get; set; }
        public virtual ICollection<T_AP_Gebaeude> T_AP_Gebaeude { get; set; }
        public virtual ICollection<T_AP_Grundstueck> T_AP_Grundstueck { get; set; }
        public virtual ICollection<T_AP_Parkplatz> T_AP_Parkplatz { get; set; }
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
        public virtual T_AP_Ref_Ort T_AP_Ref_Ort { get; set; }
        public virtual ICollection<T_AP_Sicherheit> T_AP_Sicherheit { get; set; }
        public virtual ICollection<T_AP_Standort_History> T_AP_Standort_History { get; set; }
        public virtual ICollection<T_AP_Standort> T_AP_Standort1 { get; set; }
        public virtual T_AP_Standort T_AP_Standort2 { get; set; }
        public virtual ICollection<T_REM_Ref_Vorlagen> T_REM_Ref_Vorlagen { get; set; }
        public virtual ICollection<T_SYS_Gebaeuderechte> T_SYS_Gebaeuderechte { get; set; }
        public virtual ICollection<T_SYS_Standortrechte> T_SYS_Standortrechte { get; set; }
        public virtual ICollection<T_TM_Tasks_Planung> T_TM_Tasks_Planung { get; set; }
        public virtual ICollection<T_TM_Tasks> T_TM_Tasks { get; set; }
        public virtual ICollection<T_UM_Umzug> T_UM_Umzug { get; set; }
        public virtual ICollection<T_ZO_AP_Standort_DWG> T_ZO_AP_Standort_DWG { get; set; }
        public virtual ICollection<T_ZO_MM_Standort_ServiceAnbieter> T_ZO_MM_Standort_ServiceAnbieter { get; set; }
        public virtual ICollection<T_ZO_REM_AP_Standort_Planung> T_ZO_REM_AP_Standort_Planung { get; set; }
    }
}
