//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_Parkplatz
    {
        public T_AP_Parkplatz()
        {
            this.T_AP_Parkplatz_History = new HashSet<T_AP_Parkplatz_History>();
            this.T_PM_Buchungen = new HashSet<T_PM_Buchungen>();
            this.T_TM_Tasks_Planung = new HashSet<T_TM_Tasks_Planung>();
            this.T_TM_Tasks = new HashSet<T_TM_Tasks>();
            this.T_ZO_AP_Parkplatz_AP_Belegung = new HashSet<T_ZO_AP_Parkplatz_AP_Belegung>();
            this.T_ZO_AP_Parkplatz_AP_Kontakte = new HashSet<T_ZO_AP_Parkplatz_AP_Kontakte>();
            this.T_ZO_AP_Parkplatz_AP_Ref_Kostenstelle = new HashSet<T_ZO_AP_Parkplatz_AP_Ref_Kostenstelle>();
            this.T_ZO_AP_Parkplatz_AP_Ref_Mietobjekt = new HashSet<T_ZO_AP_Parkplatz_AP_Ref_Mietobjekt>();
            this.T_ZO_AP_Parkplatz_AP_Ref_Mietvertraege = new HashSet<T_ZO_AP_Parkplatz_AP_Ref_Mietvertraege>();
            this.T_ZO_AP_Parkplatz_AP_Ref_Anmietvertraege = new HashSet<T_ZO_AP_Parkplatz_AP_Ref_Anmietvertraege>();
            this.T_ZO_AP_Parkplatz_AV_Adressen = new HashSet<T_ZO_AP_Parkplatz_AV_Adressen>();
            this.T_ZO_AP_Parkplatz_DWG = new HashSet<T_ZO_AP_Parkplatz_DWG>();
            this.T_ZO_AP_Parkplatz_Flaeche = new HashSet<T_ZO_AP_Parkplatz_Flaeche>();
            this.T_ZO_AP_Parkplatz_Reservation = new HashSet<T_ZO_AP_Parkplatz_Reservation>();
            this.T_ZO_AP_Raum_AP_Ref_Zuschlagsflaeche_Parkplatz_Geschoss = new HashSet<T_ZO_AP_Raum_AP_Ref_Zuschlagsflaeche_Parkplatz_Geschoss>();
            this.T_ZO_AP_Raum_AP_Ref_Zuschlagsflaeche_Parkplatz = new HashSet<T_ZO_AP_Raum_AP_Ref_Zuschlagsflaeche_Parkplatz>();
        }
    
        public System.Guid PP_UID { get; set; }
        public int PP_MDT_ID { get; set; }
        public Nullable<System.Guid> PP_VAR_UID { get; set; }
        public string PP_ApertureKey { get; set; }
        public Nullable<System.Guid> PP_SO_UID { get; set; }
        public Nullable<System.Guid> PP_GR_UID { get; set; }
        public Nullable<System.Guid> PP_GS_UID { get; set; }
        public Nullable<System.Guid> PP_RM_UID { get; set; }
        public Nullable<System.Guid> PP_PK_UID { get; set; }
        public Nullable<System.Guid> PP_PT_UID { get; set; }
        public Nullable<System.Guid> PP_PS_UID { get; set; }
        public Nullable<System.Guid> PP_PL_UID { get; set; }
        public Nullable<System.Guid> PP_PB_UID { get; set; }
        public string PP_Nr { get; set; }
        public string PP_Bezeichnung { get; set; }
        public string PP_Bemerkung { get; set; }
        public System.DateTime PP_DatumVon { get; set; }
        public System.DateTime PP_DatumBis { get; set; }
        public int PP_Status { get; set; }
        public Nullable<System.DateTime> PP_MutDate { get; set; }
        public string PP_MutUser { get; set; }
        public long PP_IsInnen { get; set; }
        public int PP_AnzahlPP { get; set; }
        public string C_PolygonID { get; set; }
        public string C_LiegenschaftsNr { get; set; }
        public string C_ObjektNr { get; set; }
        public string C_MieterNr { get; set; }
        public string C_VertragsNr { get; set; }
        public Nullable<int> C_AnzahlPP { get; set; }
        public string C_DrawingName { get; set; }
        public string C_GebaeudeNr { get; set; }
        public string C_UeberbauungNr { get; set; }
        public Nullable<int> C_NichtVermietbar { get; set; }
        public Nullable<int> C_Leerstand { get; set; }
        public Nullable<System.Guid> PP_HS_UID { get; set; }
        public bool PP_IsVermietbar { get; set; }
        public bool PP_IsEBF { get; set; }
        public Nullable<decimal> PP_Price { get; set; }
        public string PP_ZF_Rank { get; set; }
    
        public virtual T_AP_Geschoss T_AP_Geschoss { get; set; }
        public virtual ICollection<T_AP_Parkplatz_History> T_AP_Parkplatz_History { get; set; }
        public virtual T_AP_Raum T_AP_Raum { get; set; }
        public virtual T_AP_Ref_Haus T_AP_Ref_Haus { get; set; }
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
        public virtual T_AP_Standort T_AP_Standort { get; set; }
        public virtual T_VAR_Variante T_VAR_Variante { get; set; }
        public virtual ICollection<T_PM_Buchungen> T_PM_Buchungen { get; set; }
        public virtual ICollection<T_TM_Tasks_Planung> T_TM_Tasks_Planung { get; set; }
        public virtual ICollection<T_TM_Tasks> T_TM_Tasks { get; set; }
        public virtual ICollection<T_ZO_AP_Parkplatz_AP_Belegung> T_ZO_AP_Parkplatz_AP_Belegung { get; set; }
        public virtual ICollection<T_ZO_AP_Parkplatz_AP_Kontakte> T_ZO_AP_Parkplatz_AP_Kontakte { get; set; }
        public virtual ICollection<T_ZO_AP_Parkplatz_AP_Ref_Kostenstelle> T_ZO_AP_Parkplatz_AP_Ref_Kostenstelle { get; set; }
        public virtual ICollection<T_ZO_AP_Parkplatz_AP_Ref_Mietobjekt> T_ZO_AP_Parkplatz_AP_Ref_Mietobjekt { get; set; }
        public virtual ICollection<T_ZO_AP_Parkplatz_AP_Ref_Mietvertraege> T_ZO_AP_Parkplatz_AP_Ref_Mietvertraege { get; set; }
        public virtual ICollection<T_ZO_AP_Parkplatz_AP_Ref_Anmietvertraege> T_ZO_AP_Parkplatz_AP_Ref_Anmietvertraege { get; set; }
        public virtual ICollection<T_ZO_AP_Parkplatz_AV_Adressen> T_ZO_AP_Parkplatz_AV_Adressen { get; set; }
        public virtual ICollection<T_ZO_AP_Parkplatz_DWG> T_ZO_AP_Parkplatz_DWG { get; set; }
        public virtual ICollection<T_ZO_AP_Parkplatz_Flaeche> T_ZO_AP_Parkplatz_Flaeche { get; set; }
        public virtual ICollection<T_ZO_AP_Parkplatz_Reservation> T_ZO_AP_Parkplatz_Reservation { get; set; }
        public virtual ICollection<T_ZO_AP_Raum_AP_Ref_Zuschlagsflaeche_Parkplatz_Geschoss> T_ZO_AP_Raum_AP_Ref_Zuschlagsflaeche_Parkplatz_Geschoss { get; set; }
        public virtual ICollection<T_ZO_AP_Raum_AP_Ref_Zuschlagsflaeche_Parkplatz> T_ZO_AP_Raum_AP_Ref_Zuschlagsflaeche_Parkplatz { get; set; }
    }
}
