//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_LinkDWG
    {
        public string LI_MDT_ID { get; set; }
        public string LI_ApertureDWG { get; set; }
        public string LI_ApertureObjID { get; set; }
    }
}
