//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_Ref_SchluesselTyp
    {
        public T_AP_Ref_SchluesselTyp()
        {
            this.T_AP_Schluesselgruppe = new HashSet<T_AP_Schluesselgruppe>();
        }
    
        public System.Guid STYP_UID { get; set; }
        public int STYP_MDT_ID { get; set; }
        public Nullable<int> STYP_Code { get; set; }
        public string STYP_Kurz_DE { get; set; }
        public string STYP_Kurz_FR { get; set; }
        public string STYP_Kurz_IT { get; set; }
        public string STYP_Kurz_EN { get; set; }
        public string STYP_Lang_DE { get; set; }
        public string STYP_Lang_FR { get; set; }
        public string STYP_Lang_IT { get; set; }
        public string STYP_Lang_EN { get; set; }
        public int STYP_Status { get; set; }
        public int STYP_Sort { get; set; }
        public Nullable<int> STYP_StylizerFore { get; set; }
        public Nullable<int> STYP_StylizerBack { get; set; }
        public Nullable<int> STYP_StylizerPattern { get; set; }
        public Nullable<int> STYP_StylizerLine { get; set; }
        public bool STYP_IsDefault { get; set; }
        public Nullable<System.DateTime> STYP_DatumMut { get; set; }
        public string STYP_DatumUser { get; set; }
        public Nullable<int> STYP_FixKeyAmount { get; set; }
    
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
        public virtual ICollection<T_AP_Schluesselgruppe> T_AP_Schluesselgruppe { get; set; }
    }
}
