//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_Ref_MitarbeiterStatus
    {
        public T_AP_Ref_MitarbeiterStatus()
        {
            this.T_AP_Kontakte = new HashSet<T_AP_Kontakte>();
        }
    
        public System.Guid MS_UID { get; set; }
        public Nullable<int> MS_Code { get; set; }
        public string MS_Kurz_DE { get; set; }
        public string MS_Kurz_FR { get; set; }
        public string MS_Kurz_IT { get; set; }
        public string MS_Kurz_EN { get; set; }
        public string MS_Lang_DE { get; set; }
        public string MS_Lang_FR { get; set; }
        public string MS_Lang_IT { get; set; }
        public string MS_Lang_EN { get; set; }
        public int MS_Status { get; set; }
        public int MS_Sort { get; set; }
        public Nullable<int> MS_StylizerBack { get; set; }
        public Nullable<int> MS_StylizerPattern { get; set; }
        public Nullable<int> MS_StylizerLine { get; set; }
        public bool MS_IsDefault { get; set; }
        public Nullable<System.DateTime> MS_DatumMut { get; set; }
        public string MS_DatumUser { get; set; }
    
        public virtual ICollection<T_AP_Kontakte> T_AP_Kontakte { get; set; }
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
        public virtual T_SYS_ApertureColorToHex T_SYS_ApertureColorToHex { get; set; }
    }
}
