//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_Ref_SchluesselStatus
    {
        public T_AP_Ref_SchluesselStatus()
        {
            this.T_AP_Schluessel = new HashSet<T_AP_Schluessel>();
        }
    
        public System.Guid SLS_UID { get; set; }
        public int SLS_MDT_ID { get; set; }
        public Nullable<int> SLS_Code { get; set; }
        public string SLS_Kurz_DE { get; set; }
        public string SLS_Kurz_FR { get; set; }
        public string SLS_Kurz_IT { get; set; }
        public string SLS_Kurz_EN { get; set; }
        public string SLS_Lang_DE { get; set; }
        public string SLS_Lang_FR { get; set; }
        public string SLS_Lang_IT { get; set; }
        public string SLS_Lang_EN { get; set; }
        public int SLS_Status { get; set; }
        public int SLS_Sort { get; set; }
        public Nullable<int> SLS_StylizerFore { get; set; }
        public Nullable<int> SLS_StylizerBack { get; set; }
        public Nullable<int> SLS_StylizerPattern { get; set; }
        public Nullable<int> SLS_StylizerLine { get; set; }
        public bool SLS_IsDefault { get; set; }
        public Nullable<System.DateTime> SLS_DatumMut { get; set; }
        public string SLS_DatumUser { get; set; }
    
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
        public virtual T_SYS_ApertureColorToHex T_SYS_ApertureColorToHex { get; set; }
        public virtual ICollection<T_AP_Schluessel> T_AP_Schluessel { get; set; }
    }
}
