//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_Ref_AnlageKaeltemittel
    {
        public System.Guid AKM_UID { get; set; }
        public int AKM_MDT_ID { get; set; }
        public Nullable<int> AKM_Code { get; set; }
        public string AKM_Kurz_DE { get; set; }
        public string AKM_Kurz_FR { get; set; }
        public string AKM_Kurz_IT { get; set; }
        public string AKM_Kurz_EN { get; set; }
        public string AKM_Lang_DE { get; set; }
        public string AKM_Lang_FR { get; set; }
        public string AKM_Lang_IT { get; set; }
        public string AKM_Lang_EN { get; set; }
        public int AKM_Status { get; set; }
        public int AKM_Sort { get; set; }
        public Nullable<int> AKM_StylizerFore { get; set; }
        public Nullable<int> AKM_StylizerBack { get; set; }
        public Nullable<int> AKM_StylizerPattern { get; set; }
        public Nullable<int> AKM_StylizerLine { get; set; }
        public bool AKM_IsDefault { get; set; }
        public Nullable<System.DateTime> AKM_DatumMut { get; set; }
        public string AKM_DatumUser { get; set; }
    
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
    }
}
