//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_Ref_ZuschlagsflaechenTyp
    {
        public T_AP_Ref_ZuschlagsflaechenTyp()
        {
            this.T_AP_Raum = new HashSet<T_AP_Raum>();
        }
    
        public System.Guid ZF_UID { get; set; }
        public int ZF_MDT_ID { get; set; }
        public Nullable<int> ZF_Code { get; set; }
        public string ZF_Kurz_DE { get; set; }
        public string ZF_Kurz_FR { get; set; }
        public string ZF_Kurz_IT { get; set; }
        public string ZF_Kurz_EN { get; set; }
        public string ZF_Lang_DE { get; set; }
        public string ZF_Lang_FR { get; set; }
        public string ZF_Lang_IT { get; set; }
        public string ZF_Lang_EN { get; set; }
        public int ZF_Status { get; set; }
        public int ZF_Sort { get; set; }
        public Nullable<int> ZF_StylizerFore { get; set; }
        public Nullable<int> ZF_StylizerBack { get; set; }
        public Nullable<int> ZF_StylizerPattern { get; set; }
        public Nullable<int> ZF_StylizerLine { get; set; }
        public bool ZF_IsDefault { get; set; }
        public Nullable<System.DateTime> ZF_DatumMut { get; set; }
        public string ZF_DatumUser { get; set; }
    
        public virtual ICollection<T_AP_Raum> T_AP_Raum { get; set; }
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
    }
}
