//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_EmailVersand
    {
        public T_AP_EmailVersand()
        {
            this.T_AP_Ref_EmailAttachment = new HashSet<T_AP_Ref_EmailAttachment>();
        }
    
        public System.Guid EMAIL_UID { get; set; }
        public string EMAIL_Text { get; set; }
        public string EMAIL_Titel { get; set; }
        public string EMAIL_From { get; set; }
        public string EMAIL_To { get; set; }
        public string EMAIL_CC { get; set; }
        public Nullable<System.DateTime> EMAIL_Datum { get; set; }
        public int EMAIL_MDT_ID { get; set; }
        public bool EMAIL_Send { get; set; }
        public int EMAIL_Status { get; set; }
    
        public virtual T_AP_Ref_EmailtextKategorie T_AP_Ref_EmailtextKategorie { get; set; }
        public virtual ICollection<T_AP_Ref_EmailAttachment> T_AP_Ref_EmailAttachment { get; set; }
    }
}
