//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AP_Ref_PersonGeschlecht
    {
        public System.Guid PG_UID { get; set; }
        public int PG_MDT_ID { get; set; }
        public Nullable<int> PG_Code { get; set; }
        public string PG_Kurz_DE { get; set; }
        public string PG_Kurz_FR { get; set; }
        public string PG_Kurz_IT { get; set; }
        public string PG_Kurz_EN { get; set; }
        public string PG_Lang_DE { get; set; }
        public string PG_Lang_FR { get; set; }
        public string PG_Lang_IT { get; set; }
        public string PG_Lang_EN { get; set; }
        public int PG_Status { get; set; }
        public int PG_Sort { get; set; }
        public Nullable<int> PG_StylizerFore { get; set; }
        public Nullable<int> PG_StylizerBack { get; set; }
        public Nullable<int> PG_StylizerPattern { get; set; }
        public Nullable<int> PG_StylizerLine { get; set; }
        public bool PG_IsDefault { get; set; }
        public Nullable<System.DateTime> PG_DatumMut { get; set; }
        public string PG_DatumUser { get; set; }
    
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
    }
}
