//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_COR_Log
    {
        public string Log_ID { get; set; }
        public string Log_URL { get; set; }
        public string Log_Query { get; set; }
        public string Log_Session { get; set; }
        public string Log_Post { get; set; }
        public string Log_Browser { get; set; }
        public System.DateTime Log_Date { get; set; }
    }
}
