//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DMS_Ref_Bauphase
    {
        public System.Guid BP_UID { get; set; }
        public string BP_Code { get; set; }
        public string BP_Kurz_DE { get; set; }
        public string BP_Kurz_FR { get; set; }
        public string BP_Kurz_IT { get; set; }
        public string BP_Kurz_EN { get; set; }
        public string BP_Lang_DE { get; set; }
        public string BP_Lang_FR { get; set; }
        public string BP_Lang_IT { get; set; }
        public string BP_Lang_EN { get; set; }
        public int BP_Status { get; set; }
        public int BP_Sort { get; set; }
        public Nullable<int> BP_StylizerBack { get; set; }
        public Nullable<int> BP_StylizerPattern { get; set; }
        public Nullable<int> BP_StylizerLine { get; set; }
        public bool BP_IsDefault { get; set; }
        public Nullable<System.DateTime> BP_DatumMut { get; set; }
        public string BP_DatumUser { get; set; }
    
        public virtual T_SYS_ApertureColorToHex T_SYS_ApertureColorToHex { get; set; }
    }
}
