//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DMS_Process
    {
        public System.Guid PROC_UID { get; set; }
        public System.Guid PROC_DOC_UID { get; set; }
        public System.Guid PROC_DV_Version { get; set; }
        public Nullable<System.Guid> PROC_PROC_UID { get; set; }
        public Nullable<System.DateTime> PROC_Ende { get; set; }
        public Nullable<System.DateTime> PROC_Start { get; set; }
        public int PROC_Verantwortlich { get; set; }
        public bool PROC_IsAdminVerantwortlich { get; set; }
        public short PROC_Status { get; set; }
        public Nullable<System.DateTime> PROC_MutDate { get; set; }
        public string PROC_MutUser { get; set; }
    }
}
