//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DMS_SYS_NavEdit
    {
        public System.Guid SYSNE_UID { get; set; }
        public string SYSNE_Linktext_1 { get; set; }
        public string SYSNE_Linktext_2 { get; set; }
        public int SYSNE_Nav_Typ { get; set; }
        public int SYSNE_Status { get; set; }
    }
}
