//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DMS_Projekt
    {
        public T_DMS_Projekt()
        {
            this.T_DMS_Navigation = new HashSet<T_DMS_Navigation>();
            this.T_DMS_Projekt_History = new HashSet<T_DMS_Projekt_History>();
        }
    
        public System.Guid PJ_UID { get; set; }
        public Nullable<System.Guid> PJ_NT_UID { get; set; }
        public string PJ_Nr { get; set; }
        public string PJ_Bezeichnung { get; set; }
        public string PJ_Beschreibung { get; set; }
        public string PJ_Bemerkung { get; set; }
        public System.DateTime PJ_DatumVon { get; set; }
        public System.DateTime PJ_DatumBis { get; set; }
        public int PJ_Status { get; set; }
        public Nullable<System.DateTime> PJ_MutDate { get; set; }
        public string PJ_MutUser { get; set; }
        public int PJ_Sort { get; set; }
        public string PJ_Link { get; set; }
    
        public virtual ICollection<T_DMS_Navigation> T_DMS_Navigation { get; set; }
        public virtual ICollection<T_DMS_Projekt_History> T_DMS_Projekt_History { get; set; }
        public virtual T_DMS_Ref_NodeType T_DMS_Ref_NodeType { get; set; }
    }
}
