//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DMS_Log_UserData
    {
        public System.Guid LUD_UID { get; set; }
        public Nullable<int> LUD_BE_ID { get; set; }
        public string LUD_UserAgent { get; set; }
        public string LUD_Version { get; set; }
        public Nullable<int> LUD_MajorVersion { get; set; }
        public Nullable<double> LUD_MinorVersion { get; set; }
        public string LUD_Type { get; set; }
        public string LUD_CLRversion { get; set; }
        public Nullable<bool> LUD_Cookies { get; set; }
        public Nullable<bool> LUD_SupportsXmlHttp { get; set; }
        public Nullable<bool> LUD_JavaScript { get; set; }
        public Nullable<bool> LUD_VBScript { get; set; }
        public Nullable<bool> LUD_JavaApplets { get; set; }
        public Nullable<bool> LUD_ActiveXcontrols { get; set; }
        public string LUD_JScriptVersion { get; set; }
        public Nullable<int> LUD_MaximumHrefLength { get; set; }
        public Nullable<int> LUD_MaximumRenderedPageSize { get; set; }
        public Nullable<int> LUD_ScreenBitDepth { get; set; }
        public Nullable<int> LUD_ScreenPixelsHeight { get; set; }
        public Nullable<int> LUD_ScreenPixelsWidth { get; set; }
        public Nullable<int> LUD_ScreenCharactersWidth { get; set; }
        public Nullable<int> LUD_ScreenCharactersHeight { get; set; }
        public string LUD_PreferredResponseEncoding { get; set; }
        public string LUD_PreferredRequestEncoding { get; set; }
        public string LUD_Resolution { get; set; }
        public Nullable<System.DateTime> LUD_TimeAndDate { get; set; }
        public int LUD_Status { get; set; }
    }
}
