//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DMS_Ref_Metadaten_3
    {
        public System.Guid MD3_UID { get; set; }
        public Nullable<int> MD3_Code { get; set; }
        public string MD3_Kurz_DE { get; set; }
        public string MD3_Kurz_FR { get; set; }
        public string MD3_Kurz_IT { get; set; }
        public string MD3_Kurz_EN { get; set; }
        public string MD3_Lang_DE { get; set; }
        public string MD3_Lang_FR { get; set; }
        public string MD3_Lang_IT { get; set; }
        public string MD3_Lang_EN { get; set; }
        public int MD3_Status { get; set; }
        public int MD3_Sort { get; set; }
        public Nullable<int> MD3_StylizerFore { get; set; }
        public Nullable<int> MD3_StylizerBack { get; set; }
        public Nullable<int> MD3_StylizerPattern { get; set; }
        public Nullable<int> MD3_StylizerLine { get; set; }
        public bool MD3_IsDefault { get; set; }
        public Nullable<System.DateTime> MD3_DatumMut { get; set; }
        public string MD3_DatumUser { get; set; }
    }
}
