//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DMS_SYS_DokumentTyp
    {
        public System.Guid SYS_DT_UID { get; set; }
        public Nullable<int> SYS_DT_Code { get; set; }
        public string SYS_DT_Typ { get; set; }
        public string SYS_DT_Endung { get; set; }
        public int SYS_Status { get; set; }
    }
}
