//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EXPL_Text
    {
        public int txID { get; set; }
        public string txFRAME { get; set; }
        public Nullable<int> txKEY { get; set; }
        public string txName { get; set; }
        public string txText1 { get; set; }
        public string txText2 { get; set; }
        public string txText3 { get; set; }
        public string txText4 { get; set; }
        public int EXTXT_Status { get; set; }
    }
}
