//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EXPL_FunktionKommando
    {
        public int fcID { get; set; }
        public string fcKEY { get; set; }
        public Nullable<int> fcPos { get; set; }
        public string fcName1 { get; set; }
        public string fcName2 { get; set; }
        public string fcName3 { get; set; }
        public string fcName4 { get; set; }
        public int EXFUCMD_Status { get; set; }
    }
}
