//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_FMS_Translation_Export
    {
        public System.Guid FT_UID { get; set; }
        public string FT_Ch { get; set; }
        public string FT_De { get; set; }
        public string FT_En { get; set; }
        public string FT_Fr { get; set; }
        public string FT_It { get; set; }
        public string FT_Ru { get; set; }
        public string FT_Parameter { get; set; }
        public int FT_Status { get; set; }
    }
}
