//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_FMS_ZO_Navigation_Benutzer
    {
        public System.Guid NABE_UID { get; set; }
        public int NABE_BE_ID { get; set; }
        public System.Guid NABE_NA_UID { get; set; }
        public bool NABE_Show { get; set; }
        public int NABE_Status { get; set; }
    
        public virtual T_Benutzer T_Benutzer { get; set; }
        public virtual T_FMS_Navigation T_FMS_Navigation { get; set; }
    }
}
