//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Import_PLZ_Region
    {
        public System.Guid PLZ_UID { get; set; }
        public Nullable<int> PLZ_Nummer { get; set; }
        public string PLZ_Varchar { get; set; }
        public string PLZ_Ort1 { get; set; }
        public string PLZ_Ort2 { get; set; }
        public string PLZ_Kanton { get; set; }
    }
}
