//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Image
    {
        public int Index { get; set; }
        public int BE_ID { get; set; }
        public Nullable<System.Guid> Reference { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> Height { get; set; }
        public string Mime { get; set; }
        public string Name { get; set; }
        public Nullable<int> Width { get; set; }
        public System.DateTime Created { get; set; }
        public int IMG_Status { get; set; }
    }
}
