//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MM_Umzug_Bestand
    {
        public T_MM_Umzug_Bestand()
        {
            this.T_ZO_MM_Bestand_Umzug = new HashSet<T_ZO_MM_Bestand_Umzug>();
        }
    
        public System.Guid MMUB_UID { get; set; }
        public System.Guid MMUB_MMA_UID { get; set; }
        public string MMUB_Bezeichnung { get; set; }
        public string MMUB_UmzugID { get; set; }
        public System.Guid MMUB_MMST_UID { get; set; }
        public Nullable<int> MMUB_BevorzugtUmzugWoche { get; set; }
        public Nullable<System.DateTime> MMUB_UmzugDatum { get; set; }
        public int MMUB_UmzugKartons { get; set; }
        public Nullable<System.Guid> MMUB_AP_UID_Alt { get; set; }
        public Nullable<System.Guid> MMUB_AP_UID_Neu { get; set; }
        public int MMUB_Status { get; set; }
        public Nullable<System.DateTime> MMUB_Datum_Erstellung { get; set; }
        public Nullable<System.DateTime> MMUB_Datum_Aenderung { get; set; }
        public Nullable<System.DateTime> MMUB_Datum_Eingereicht { get; set; }
        public string MMUB_Kommentar { get; set; }
        public Nullable<int> MMUB_BevorzugtUmzugJahr { get; set; }
        public string MMUB_AblehnungsGrund { get; set; }
        public bool MMUB_AP_Bestand_OK { get; set; }
    
        public virtual T_AP_Arbeitsplatz T_AP_Arbeitsplatz { get; set; }
        public virtual T_AP_Arbeitsplatz T_AP_Arbeitsplatz1 { get; set; }
        public virtual T_MM_Antrag T_MM_Antrag { get; set; }
        public virtual T_MM_Ref_Status T_MM_Ref_Status { get; set; }
        public virtual ICollection<T_ZO_MM_Bestand_Umzug> T_ZO_MM_Bestand_Umzug { get; set; }
    }
}
