//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MM_Ref_LetzteEMailAusfuehrungsZeit
    {
        public System.Guid MMMAZ_UID { get; set; }
        public System.DateTime MMMAZ_Zeit { get; set; }
        public int MMMAZ_Status { get; set; }
    }
}
