//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MM_Antrag
    {
        public T_MM_Antrag()
        {
            this.T_MM_Antrag_History = new HashSet<T_MM_Antrag_History>();
            this.T_MM_Antrag_Kommentar = new HashSet<T_MM_Antrag_Kommentar>();
            this.T_MM_Umzug_Bestand = new HashSet<T_MM_Umzug_Bestand>();
            this.T_MM_Umzug = new HashSet<T_MM_Umzug>();
        }
    
        public System.Guid MMA_UID { get; set; }
        public int MMA_AntragID { get; set; }
        public string MMA_Beschreibung { get; set; }
        public System.Guid MMA_MMST_UID { get; set; }
        public Nullable<int> MMA_BE_ID_Antragsteller { get; set; }
        public Nullable<int> MMA_BE_ID_UmzugManager { get; set; }
        public Nullable<bool> MMA_IsBestandUmzug { get; set; }
        public int MMA_Status { get; set; }
        public Nullable<System.DateTime> MMA_Datum_Erstellung { get; set; }
        public Nullable<System.DateTime> MMA_Datum_Aenderung { get; set; }
        public Nullable<System.DateTime> MMA_Datum_Eingereicht { get; set; }
        public Nullable<System.Guid> MMA_MMUT_UID { get; set; }
    
        public virtual ICollection<T_MM_Antrag_History> T_MM_Antrag_History { get; set; }
        public virtual ICollection<T_MM_Antrag_Kommentar> T_MM_Antrag_Kommentar { get; set; }
        public virtual T_MM_Ref_UmzugTyp T_MM_Ref_UmzugTyp { get; set; }
        public virtual T_MM_Ref_Status T_MM_Ref_Status { get; set; }
        public virtual ICollection<T_MM_Umzug_Bestand> T_MM_Umzug_Bestand { get; set; }
        public virtual ICollection<T_MM_Umzug> T_MM_Umzug { get; set; }
    }
}
