//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MM_Ref_UmzugTyp
    {
        public T_MM_Ref_UmzugTyp()
        {
            this.T_MM_Antrag = new HashSet<T_MM_Antrag>();
        }
    
        public System.Guid MMUT_UID { get; set; }
        public Nullable<int> MMUT_Code { get; set; }
        public string MMUT_Kurz_de { get; set; }
        public string MMUT_Kurz_fr { get; set; }
        public string MMUT_Kurz_it { get; set; }
        public string MMUT_Kurz_en { get; set; }
        public string MMUT_Lang_de { get; set; }
        public string MMUT_Lang_fr { get; set; }
        public string MMUT_Lang_it { get; set; }
        public string MMUT_Lang_en { get; set; }
        public int MMUT_Status { get; set; }
        public int MMUT_Sort { get; set; }
        public bool MMUT_IsDefault { get; set; }
        public Nullable<int> MMUT_StylizerFore { get; set; }
        public Nullable<int> MMUT_StylizerPattern { get; set; }
        public Nullable<int> MMUT_StylizerLine { get; set; }
        public int MMUT_MDT_ID { get; set; }
    
        public virtual ICollection<T_MM_Antrag> T_MM_Antrag { get; set; }
        public virtual T_SYS_ApertureColorToHex T_SYS_ApertureColorToHex { get; set; }
    }
}
