//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MM_Ref_UmzugTyp
    {
        public T_MM_Ref_UmzugTyp()
        {
            this.T_MM_Antrag = new HashSet<T_MM_Antrag>();
        }
    
        public System.Guid MMUT_UID { get; set; }
        public Nullable<int> MMUT_Code { get; set; }
        public string MMUT_Kurz_de { get; set; }
        public string MMUT_Kurz_fr { get; set; }
        public string MMUT_Kurz_it { get; set; }
        public string MMUT_Kurz_en { get; set; }
        public string MMUT_Lang_de { get; set; }
        public string MMUT_Lang_fr { get; set; }
        public string MMUT_Lang_it { get; set; }
        public string MMUT_Lang_en { get; set; }
        public int MMUT_Status { get; set; }
        public int MMUT_Sort { get; set; }
        public bool MMUT_IsDefault { get; set; }
        public Nullable<int> MMUT_StylizerBack { get; set; }
        public Nullable<int> MMUT_StylizerFore { get; set; }
        public Nullable<int> MMUT_StylizerPattern { get; set; }
        public Nullable<int> MMUT_StylizerLine { get; set; }
        public int MMUT_MDT_ID { get; set; }
    
        public virtual ICollection<T_MM_Antrag> T_MM_Antrag { get; set; }
        public virtual T_SYS_ApertureColorToHex T_SYS_ApertureColorToHex { get; set; }
    }
}
