//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MM_Antrag_Kommentar
    {
        public System.Guid MMAKM_UID { get; set; }
        public Nullable<System.Guid> MMAKM_MMA_UID { get; set; }
        public string MMAKM_Kommentar { get; set; }
        public string MMAKM_User { get; set; }
        public System.DateTime MMAKM_Datum { get; set; }
        public int MMAKM_Status { get; set; }
    
        public virtual T_MM_Antrag T_MM_Antrag { get; set; }
    }
}
