//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OR_EMail
    {
        public int ORE_Index { get; set; }
        public Nullable<System.DateTime> ORE_dateFrom { get; set; }
        public Nullable<System.DateTime> ORE_dateTo { get; set; }
        public string ORE_Body { get; set; }
        public string ORE_From { get; set; }
        public string ORE_Location { get; set; }
        public string ORE_Parameter { get; set; }
        public bool ORE_Sent { get; set; }
        public string ORE_Subject { get; set; }
        public string ORE_To { get; set; }
        public System.DateTime ORE_Created { get; set; }
        public int ORE_Status { get; set; }
    }
}
