//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OR_Assignment_Services
    {
        public System.Guid ORAS_UID { get; set; }
        public System.Guid ORAS_ORA_UID { get; set; }
        public System.Guid ORAS_ORSO_UID { get; set; }
        public System.DateTime ORAS_Created { get; set; }
        public int ORAS_Status { get; set; }
    }
}
