//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OR_Service_Categories
    {
        public System.Guid ORSC_UID { get; set; }
        public string ORSC_Name_De { get; set; }
        public string ORSC_Name_Fr { get; set; }
        public string ORSC_Name_En { get; set; }
        public string ORSC_Name_It { get; set; }
        public int ORSC_Status { get; set; }
        public System.DateTime ORSC_Created { get; set; }
    }
}
