//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OR_Configuration
    {
        public int ORC_Index { get; set; }
        public string ORC_Key { get; set; }
        public string ORC_Value { get; set; }
        public System.DateTime ORC_Created { get; set; }
        public int ORC_Status { get; set; }
    }
}
