//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OR_Ref_General
    {
        public System.Guid ORT_UID { get; set; }
        public string ORT_Code { get; set; }
        public string ORT_Code_Parent { get; set; }
        public string ORT_BookFieldName { get; set; }
        public bool ORT_hasServices { get; set; }
        public bool ORT_isBookable { get; set; }
        public string ORT_Kurz_De { get; set; }
        public string ORT_Kurz_Fr { get; set; }
        public string ORT_Kurz_En { get; set; }
        public string ORT_Kurz_It { get; set; }
        public string ORT_PriceFieldName { get; set; }
        public int ORT_Sort { get; set; }
        public int ORT_Tax { get; set; }
        public string ORT_Tablename { get; set; }
        public string ORT_View_Assets { get; set; }
        public string ORT_View_Category { get; set; }
        public string ORT_View_Datagrid { get; set; }
        public string ORT_View_Type { get; set; }
        public int ORT_Status { get; set; }
    }
}
