//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OR_Configuration
    {
        public int ORC_Index { get; set; }
        public string ORC_Key { get; set; }
        public string ORC_Value { get; set; }
        public System.DateTime ORC_Created { get; set; }
        public int ORC_Status { get; set; }
    }
}
