//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OV_Ref_BelegungArt
    {
        public System.Guid BELA_UID { get; set; }
        public int BELA_MDT_ID { get; set; }
        public Nullable<int> BELA_Code { get; set; }
        public string BELA_Kurz_DE { get; set; }
        public string BELA_Kurz_FR { get; set; }
        public string BELA_Kurz_IT { get; set; }
        public string BELA_Kurz_EN { get; set; }
        public string BELA_Lang_DE { get; set; }
        public string BELA_Lang_FR { get; set; }
        public string BELA_Lang_IT { get; set; }
        public string BELA_Lang_EN { get; set; }
        public int BELA_Status { get; set; }
        public int BELA_Sort { get; set; }
        public Nullable<int> BELA_StylizerFore { get; set; }
        public Nullable<int> BELA_StylizerBack { get; set; }
        public Nullable<int> BELA_StylizerPattern { get; set; }
        public Nullable<int> BELA_StylizerLine { get; set; }
        public bool BELA_IsDefault { get; set; }
        public Nullable<System.DateTime> BELA_DatumMut { get; set; }
        public string BELA_DatumUser { get; set; }
    
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
    }
}
