//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PM_Buchungen
    {
        public System.Guid BU_UID { get; set; }
        public Nullable<System.Guid> BU_PP_UID { get; set; }
        public Nullable<System.DateTime> BU_DatumVon { get; set; }
        public Nullable<System.DateTime> BU_DatumBis { get; set; }
        public string BU_Name { get; set; }
        public string BU_Vorname { get; set; }
        public string BU_Firma { get; set; }
        public string BU_Autokennzeichen { get; set; }
        public string BU_Bemerkungen { get; set; }
        public Nullable<System.Guid> BU_ZT_UID_ZeitVon { get; set; }
        public Nullable<System.Guid> BU_ZT_UID_ZeitBis { get; set; }
        public int BU_Status { get; set; }
        public Nullable<System.DateTime> BU_MutDate { get; set; }
        public string BU_MutUser { get; set; }
        public int BU_MDT_ID { get; set; }
    
        public virtual T_AP_Parkplatz T_AP_Parkplatz { get; set; }
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
        public virtual T_SYS_Ref_Zeit T_SYS_Ref_Zeit { get; set; }
        public virtual T_SYS_Ref_Zeit T_SYS_Ref_Zeit1 { get; set; }
    }
}
