//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_REM_Ref_RaumName
    {
        public T_REM_Ref_RaumName()
        {
            this.T_ZO_REM_AP_Raum_Ausstattung_Kalk = new HashSet<T_ZO_REM_AP_Raum_Ausstattung_Kalk>();
            this.T_ZO_REM_AP_Raum_Ausstattung = new HashSet<T_ZO_REM_AP_Raum_Ausstattung>();
        }
    
        public System.Guid REMRN_UID { get; set; }
        public string REMRN_Code { get; set; }
        public string REMRN_Kurz_de { get; set; }
        public string REMRN_Kurz_fr { get; set; }
        public string REMRN_Kurz_it { get; set; }
        public string REMRN_Kurz_en { get; set; }
        public string REMRN_Lang_de { get; set; }
        public string REMRN_Lang_fr { get; set; }
        public string REMRN_Lang_it { get; set; }
        public string REMRN_Lang_en { get; set; }
        public int REMRN_Status { get; set; }
        public int REMRN_Sort { get; set; }
        public bool REMRN_IsDefault { get; set; }
        public Nullable<int> REMRN_StylizerBack { get; set; }
        public Nullable<int> REMRN_StylizerFore { get; set; }
        public Nullable<int> REMRN_StylizerPattern { get; set; }
        public Nullable<int> REMRN_StylizerLine { get; set; }
    
        public virtual ICollection<T_ZO_REM_AP_Raum_Ausstattung_Kalk> T_ZO_REM_AP_Raum_Ausstattung_Kalk { get; set; }
        public virtual ICollection<T_ZO_REM_AP_Raum_Ausstattung> T_ZO_REM_AP_Raum_Ausstattung { get; set; }
    }
}
