//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_RPT_Reports
    {
        public System.Guid RE_UID { get; set; }
        public Nullable<System.Guid> RE_RE_UID { get; set; }
        public Nullable<int> RE_Code { get; set; }
        public string RE_Text_DE { get; set; }
        public string RE_Text_FR { get; set; }
        public string RE_Text_IT { get; set; }
        public string RE_Text_EN { get; set; }
        public string RE_Link { get; set; }
        public int RE_Sort { get; set; }
        public int RE_Status { get; set; }
    }
}
