//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SYS_Berechtigung_Felder
    {
        public int BF_ID { get; set; }
        public int BF_BT_ID { get; set; }
        public string BF_Feldname { get; set; }
        public string BF_Feldbezeichnung { get; set; }
        public string BF_Registerbezeichnung { get; set; }
        public int BF_Sort_Register { get; set; }
        public int BF_Sort { get; set; }
        public bool BF_IsOnlyShow { get; set; }
        public bool BF_IsCalc { get; set; }
        public Nullable<System.DateTime> BF_ErfDate { get; set; }
        public int BF_Status { get; set; }
        public string BF_OBJT_Code { get; set; }
        public string BF_Kunde { get; set; }
    }
}
