//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SYS_Layersetrechte
    {
        public System.Guid LYR_UID { get; set; }
        public int LYR_GRANTEE_ID { get; set; }
        public string LYR_GRANTEE { get; set; }
        public Nullable<System.Guid> LYR_LY_UID { get; set; }
        public bool LYR_IsRead { get; set; }
        public int LYR_Status { get; set; }
        public int LYR_MDT_ID { get; set; }
    
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
        public virtual T_SYS_Ref_Layerset T_SYS_Ref_Layerset { get; set; }
    }
}
