//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SYS_Settings_System
    {
        public System.Guid SYS_Uid { get; set; }
        public bool SYS_Sprache_IsDe { get; set; }
        public bool SYS_Sprache_IsFr { get; set; }
        public bool SYS_Sprache_IsIt { get; set; }
        public bool SYS_Sprache_IsEn { get; set; }
    }
}
