//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SYS_Language_DayNames
    {
        public int SYSDAYS_SYSLANG_LCID { get; set; }
        public int SYSDAYS_DayOfWeekIndexBaseZero { get; set; }
        public Nullable<int> SYSDAYS_DayOfWeekIndexBaseOne { get; set; }
        public string SYSDAYS_SYSLANG_IetfLanguageTag { get; set; }
        public string SYSDAYS_Name { get; set; }
        public string SYSDAYS_LowerCaseName { get; set; }
        public string SYSDAYS_UpperCaseName { get; set; }
        public string SYSDAYS_TitleCaseName { get; set; }
        public string SYSDAYS_AbbreviatedName { get; set; }
        public string SYSDAYS_LowerCaseAbbreviatedName { get; set; }
        public string SYSDAYS_UpperCaseAbbreviatedName { get; set; }
        public string SYSDAYS_TitleCaseAbbreviatedName { get; set; }
        public string SYSDAYS_ShortestName { get; set; }
        public string SYSDAYS_LowerCaseShortestName { get; set; }
        public string SYSDAYS_UpperCaseShortestName { get; set; }
        public string SYSDAYS_TitleCaseShortestName { get; set; }
    }
}
