//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SYS_Ref_Datentyp
    {
        public T_SYS_Ref_Datentyp()
        {
            this.T_AP_Ref_DokumentMetadaten = new HashSet<T_AP_Ref_DokumentMetadaten>();
        }
    
        public System.Guid DT_UID { get; set; }
        public int DT_MDT_ID { get; set; }
        public Nullable<int> DT_Code { get; set; }
        public string DT_Kurz_DE { get; set; }
        public string DT_Kurz_FR { get; set; }
        public string DT_Kurz_IT { get; set; }
        public string DT_Kurz_EN { get; set; }
        public string DT_Lang_DE { get; set; }
        public string DT_Lang_FR { get; set; }
        public string DT_Lang_IT { get; set; }
        public string DT_Lang_EN { get; set; }
        public int DT_Status { get; set; }
        public int DT_Sort { get; set; }
        public Nullable<int> DT_StylizerFore { get; set; }
        public Nullable<int> DT_StylizerBack { get; set; }
        public Nullable<int> DT_StylizerPattern { get; set; }
        public Nullable<int> DT_StylizerLine { get; set; }
        public bool DT_IsDefault { get; set; }
        public Nullable<System.DateTime> DT_DatumMut { get; set; }
        public string DT_DatumUser { get; set; }
    
        public virtual ICollection<T_AP_Ref_DokumentMetadaten> T_AP_Ref_DokumentMetadaten { get; set; }
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
        public virtual T_SYS_ApertureColorToHex T_SYS_ApertureColorToHex { get; set; }
    }
}
