//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SYS_Berechtigung_Tabellen
    {
        public int BT_ID { get; set; }
        public string BT_Tabelle { get; set; }
        public string BT_Bezeichnung { get; set; }
        public int BT_Status { get; set; }
        public string BT_OBJT_Code { get; set; }
    }
}
