//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SYS_Ref_BackOfficeSubMenue
    {
        public T_SYS_Ref_BackOfficeSubMenue()
        {
            this.T_SYS_BackOfficeMenuerechte = new HashSet<T_SYS_BackOfficeMenuerechte>();
        }
    
        public System.Guid BOSM_UID { get; set; }
        public Nullable<int> BOSM_Code { get; set; }
        public string BOSM_Kurz_DE { get; set; }
        public string BOSM_Kurz_FR { get; set; }
        public string BOSM_Kurz_IT { get; set; }
        public string BOSM_Kurz_EN { get; set; }
        public string BOSM_Lang_DE { get; set; }
        public string BOSM_Lang_FR { get; set; }
        public string BOSM_Lang_IT { get; set; }
        public string BOSM_Lang_EN { get; set; }
        public int BOSM_Status { get; set; }
        public int BOSM_Sort { get; set; }
        public Nullable<int> BOSM_StylizerBack { get; set; }
        public Nullable<int> BOSM_StylizerPattern { get; set; }
        public Nullable<int> BOSM_StylizerLine { get; set; }
        public bool BOSM_IsDefault { get; set; }
    
        public virtual T_SYS_ApertureColorToHex T_SYS_ApertureColorToHex { get; set; }
        public virtual ICollection<T_SYS_BackOfficeMenuerechte> T_SYS_BackOfficeMenuerechte { get; set; }
        public virtual T_SYS_Ref_BackOfficeMenue T_SYS_Ref_BackOfficeMenue { get; set; }
    }
}
