//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SYS_Settings
    {
        public T_SYS_Settings()
        {
            this.T_ZO_SYS_Settings_AP_Ref_Mandant = new HashSet<T_ZO_SYS_Settings_AP_Ref_Mandant>();
        }
    
        public System.Guid SET_UID { get; set; }
        public string SET_Code { get; set; }
        public string SET_Typ { get; set; }
        public string SET_Bezeichnung { get; set; }
        public short SET_Status { get; set; }
        public int SET_Sort { get; set; }
        public string SET_Bemerkung { get; set; }
        public string SET_Values { get; set; }
    
        public virtual ICollection<T_ZO_SYS_Settings_AP_Ref_Mandant> T_ZO_SYS_Settings_AP_Ref_Mandant { get; set; }
    }
}
