//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SYS_Legendenkonfiguration
    {
        public System.Guid LCONF_UID { get; set; }
        public Nullable<int> LCONF_MDT_ID { get; set; }
        public string LCONF_MDT_Lang_DE { get; set; }
        public string LCONF_LegendItem { get; set; }
        public string LCONF_FormatString { get; set; }
        public string LCONF_CustomHtml { get; set; }
        public Nullable<int> LCONF_MaxEntries { get; set; }
        public string LCONF_FontFamily { get; set; }
        public Nullable<int> LCONF_Size { get; set; }
        public Nullable<double> LCONF_PosX { get; set; }
        public Nullable<double> LCONF_PosY { get; set; }
        public Nullable<double> LCONF_Width { get; set; }
        public Nullable<double> LCONF_Height { get; set; }
        public Nullable<double> LCONF_Angle { get; set; }
        public Nullable<bool> LCONF_MapPath { get; set; }
        public Nullable<bool> LCONF_MandantLogo { get; set; }
        public string LCONF_FileName { get; set; }
        public string LCONF_FileBase64 { get; set; }
        public Nullable<bool> LCONF_Outline { get; set; }
        public string LCONF_OutlineColor { get; set; }
        public Nullable<int> LCONF_Sort { get; set; }
        public Nullable<int> LCONF_Status { get; set; }
        public string LCONF_FormatString_DE { get; set; }
        public string LCONF_FormatString_FR { get; set; }
        public string LCONF_FormatString_IT { get; set; }
        public string LCONF_FormatString_EN { get; set; }
    
        public virtual T_SYS_Ref_PapierFormat T_SYS_Ref_PapierFormat { get; set; }
    }
}
