//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TM_Ref_FilterAnzeige
    {
        public System.Guid FIA_UID { get; set; }
        public Nullable<int> FIA_Code { get; set; }
        public string FIA_Kurz_DE { get; set; }
        public string FIA_Kurz_FR { get; set; }
        public string FIA_Kurz_IT { get; set; }
        public string FIA_Kurz_EN { get; set; }
        public string FIA_Lang_DE { get; set; }
        public string FIA_Lang_FR { get; set; }
        public string FIA_Lang_IT { get; set; }
        public string FIA_Lang_EN { get; set; }
        public int FIA_Status { get; set; }
        public int FIA_Sort { get; set; }
        public Nullable<int> FIA_StylizerFore { get; set; }
        public Nullable<int> FIA_StylizerBack { get; set; }
        public Nullable<int> FIA_StylizerPattern { get; set; }
        public Nullable<int> FIA_StylizerLine { get; set; }
        public bool FIA_IsDefault { get; set; }
        public Nullable<System.DateTime> FIA_DatumMut { get; set; }
        public string FIA_DatumUser { get; set; }
    }
}
