//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TM_Schedule
    {
        public System.Guid TPS_TPL_UID { get; set; }
        public System.Guid TPS_TART_UID { get; set; }
        public System.DateTime TPS_From { get; set; }
        public System.DateTime TPS_To { get; set; }
        public int TPS_Year { get; set; }
    }
}
