//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TM_Ref_Abteilung
    {
        public T_TM_Ref_Abteilung()
        {
            this.T_TM_Tasks_Planung = new HashSet<T_TM_Tasks_Planung>();
            this.T_TM_Tasks = new HashSet<T_TM_Tasks>();
        }
    
        public System.Guid ABT_UID { get; set; }
        public Nullable<int> ABT_Code { get; set; }
        public string ABT_Kurz_DE { get; set; }
        public string ABT_Kurz_FR { get; set; }
        public string ABT_Kurz_IT { get; set; }
        public string ABT_Kurz_EN { get; set; }
        public string ABT_Lang_DE { get; set; }
        public string ABT_Lang_FR { get; set; }
        public string ABT_Lang_IT { get; set; }
        public string ABT_Lang_EN { get; set; }
        public int ABT_Status { get; set; }
        public int ABT_Sort { get; set; }
        public Nullable<int> ABT_StylizerBack { get; set; }
        public Nullable<int> ABT_StylizerPattern { get; set; }
        public Nullable<int> ABT_StylizerLine { get; set; }
        public bool ABT_IsDefault { get; set; }
        public Nullable<System.DateTime> ABT_DatumMut { get; set; }
        public string ABT_DatumUser { get; set; }
    
        public virtual T_SYS_ApertureColorToHex T_SYS_ApertureColorToHex { get; set; }
        public virtual ICollection<T_TM_Tasks_Planung> T_TM_Tasks_Planung { get; set; }
        public virtual ICollection<T_TM_Tasks> T_TM_Tasks { get; set; }
    }
}
