//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_UW_Verbrauch
    {
        public System.Guid UWVB_UID { get; set; }
        public System.Guid UWVB_UWBR_UID { get; set; }
        public System.Guid UWVB_UWPOS_UID { get; set; }
        public double UWVB_Wert { get; set; }
        public string UWVB_Bemerkung { get; set; }
        public int UWVB_Status { get; set; }
        public System.DateTime UWVB_ErfDate { get; set; }
        public string UWVB_MutUser { get; set; }
        public Nullable<System.DateTime> UWVB_MutDate { get; set; }
        public int UWVB_Jahr { get; set; }
        public int UWVB_Monat { get; set; }
        public double UWVB_Kosten { get; set; }
        public System.DateTime UWVB_DatumVon { get; set; }
        public System.DateTime UWVB_DatumBis { get; set; }
    
        public virtual T_AP_Gebaeude T_AP_Gebaeude { get; set; }
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
    }
}
