//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_VM_Ref_Vertragstyp
    {
        public T_VM_Ref_Vertragstyp()
        {
            this.T_VM_Vertraege = new HashSet<T_VM_Vertraege>();
        }
    
        public System.Guid VT_UID { get; set; }
        public Nullable<int> VT_Code { get; set; }
        public string VT_Kurz_DE { get; set; }
        public string VT_Kurz_FR { get; set; }
        public string VT_Kurz_IT { get; set; }
        public string VT_Kurz_EN { get; set; }
        public string VT_Lang_DE { get; set; }
        public string VT_Lang_FR { get; set; }
        public string VT_Lang_IT { get; set; }
        public string VT_Lang_EN { get; set; }
        public int VT_Status { get; set; }
        public int VT_Sort { get; set; }
        public Nullable<int> VT_StylizerBack { get; set; }
        public Nullable<int> VT_StylizerPattern { get; set; }
        public Nullable<int> VT_StylizerLine { get; set; }
        public bool VT_IsDefault { get; set; }
        public Nullable<System.DateTime> VT_DatumMut { get; set; }
        public string VT_DatumUser { get; set; }
    
        public virtual T_SYS_ApertureColorToHex T_SYS_ApertureColorToHex { get; set; }
        public virtual ICollection<T_VM_Vertraege> T_VM_Vertraege { get; set; }
    }
}
