//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_VWS_PortalTree
    {
        public System.Guid VPT_UID { get; set; }
        public string VPT_Customer { get; set; }
        public string VPT_Key { get; set; }
        public Nullable<bool> VTP_Rel_ROOT { get; set; }
        public Nullable<bool> VTP_Rel_SO { get; set; }
        public Nullable<bool> VTP_Rel_SK { get; set; }
        public Nullable<bool> VTP_Rel_STR { get; set; }
        public Nullable<bool> VTP_Rel_GB { get; set; }
        public Nullable<bool> VTP_Rel_GS { get; set; }
        public Nullable<bool> VTP_Rel_KA { get; set; }
        public Nullable<bool> VTP_Rel_KAT { get; set; }
    }
}
