//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ZO_AP_Standort_DWG
    {
        public System.Guid ZO_SODWG_UID { get; set; }
        public System.Guid ZO_SODWG_SO_UID { get; set; }
        public string ZO_SODWG_ApertureDWG { get; set; }
        public System.DateTime ZO_SODWG_DatumVon { get; set; }
        public System.DateTime ZO_SODWG_DatumBis { get; set; }
        public string ZO_SODWG_ApertureObjID { get; set; }
        public int ZO_SODWG_Status { get; set; }
        public string ZO_SODWG_DWGID { get; set; }
    
        public virtual T_AP_Standort T_AP_Standort { get; set; }
    }
}
