//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ZO_AP_Anschluss_DWG
    {
        public System.Guid ZO_ANDWG_UID { get; set; }
        public System.Guid ZO_ANDWG_AN_UID { get; set; }
        public string ZO_ANDWG_ApertureDWG { get; set; }
        public System.DateTime ZO_ANDWG_DatumVon { get; set; }
        public System.DateTime ZO_ANDWG_DatumBis { get; set; }
        public string ZO_ANDWG_ApertureObjID { get; set; }
        public int ZO_ANDWG_Status { get; set; }
        public string ZO_ANDWG_DWGID { get; set; }
    
        public virtual T_AP_Anschluss T_AP_Anschluss { get; set; }
    }
}
