//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ZO_OV_Ref_ObjektPolygon
    {
        public System.Guid ZO_OBJP_UID { get; set; }
        public System.Guid ZO_OBJP_LY_UID { get; set; }
        public int ZO_OBJP_MDT_ID { get; set; }
        public System.Guid ZO_OBJP_DK_UID { get; set; }
        public double ZO_OBJP_Left { get; set; }
        public double ZO_OBJP_Top { get; set; }
        public int ZO_OBJP_Width { get; set; }
        public int ZO_OBJP_Height { get; set; }
        public int ZO_OBJP_Angle { get; set; }
        public string ZO_OBJP_DWG { get; set; }
        public int ZO_OBJP_DistanceX { get; set; }
        public int ZO_OBJP_DistanceY { get; set; }
        public double ZO_OBJP_CenterX { get; set; }
        public double ZO_OBJP_CenterY { get; set; }
        public double ZO_OBJP_L { get; set; }
        public double ZO_OBJP_R { get; set; }
        public double ZO_OBJP_T { get; set; }
        public double ZO_OBJP_B { get; set; }
        public int ZO_OBJP_Status { get; set; }
        public int ZO_OBJP_Sort { get; set; }
    
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
        public virtual T_SYS_Ref_Layerset T_SYS_Ref_Layerset { get; set; }
    }
}
