//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ZO_AP_Mobiliar_DWG
    {
        public System.Guid ZO_MODWG_UID { get; set; }
        public System.Guid ZO_MODWG_MO_UID { get; set; }
        public string ZO_MODWG_ApertureDWG { get; set; }
        public System.DateTime ZO_MODWG_DatumVon { get; set; }
        public System.DateTime ZO_MODWG_DatumBis { get; set; }
        public string ZO_MODWG_ApertureObjID { get; set; }
        public int ZO_MODWG_Status { get; set; }
        public string ZO_MODWG_DWGID { get; set; }
    
        public virtual T_AP_Mobiliar T_AP_Mobiliar { get; set; }
    }
}
