//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ZO_AP_Aussenobjekt_AP_Ref_AussenobjektAusbauten
    {
        public System.Guid ZO_AOABT_UID { get; set; }
        public System.Guid ZO_AOABT_AO_UID { get; set; }
        public System.Guid ZO_AOABT_ABT_UID { get; set; }
        public int ZO_AOABT_Menge { get; set; }
        public int ZO_AOABT_Status { get; set; }
    
        public virtual T_AP_Aussenobjekt T_AP_Aussenobjekt { get; set; }
        public virtual T_AP_Ref_AussenobjektAusbauten T_AP_Ref_AussenobjektAusbauten { get; set; }
    }
}
