//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ZO_AP_Grundstueck_DWG
    {
        public System.Guid ZO_GRUDWG_UID { get; set; }
        public System.Guid ZO_GRUDWG_GRU_UID { get; set; }
        public string ZO_GRUDWG_ApertureDWG { get; set; }
        public System.DateTime ZO_GRUDWG_DatumVon { get; set; }
        public System.DateTime ZO_GRUDWG_DatumBis { get; set; }
        public string ZO_GRUDWG_ApertureObjID { get; set; }
        public int ZO_GRUDWG_Status { get; set; }
        public string ZO_GRUDWG_DWGID { get; set; }
    
        public virtual T_AP_Grundstueck T_AP_Grundstueck { get; set; }
    }
}
