//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ZO_AP_MarkDWG
    {
        public string ZO_MDRMDWG_ApertureObjID { get; set; }
        public int ZO_MDRMDWG_BE_ID { get; set; }
        public Nullable<int> ZO_MDRMDWG_COL { get; set; }
    
        public virtual T_Benutzer T_Benutzer { get; set; }
    }
}
