//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ZO_AP_Kontakte_AP_Ref_Funktionen
    {
        public System.Guid ZO_KTKF_UID { get; set; }
        public Nullable<System.Guid> ZO_KTKF_KT_UID { get; set; }
        public Nullable<System.Guid> ZO_KTKF_KF_UID { get; set; }
        public int ZO_KTKF_Status { get; set; }
    
        public virtual T_AP_Kontakte T_AP_Kontakte { get; set; }
        public virtual T_AP_Ref_KontakFunktion T_AP_Ref_KontakFunktion { get; set; }
    }
}
