//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ZO_REM_AP_Planung_Ref_Raum
    {
        public int ZO_RMRPR_REMSP_Nr { get; set; }
        public System.Guid ZO_RMRPR_RM_UID { get; set; }
        public Nullable<int> ZO_RMRPR_Status { get; set; }
        public string ZO_RMRPR_Reinigungstag { get; set; }
        public string ZO_RMRPR_Sort { get; set; }
    
        public virtual T_AP_Raum T_AP_Raum { get; set; }
        public virtual T_ZO_REM_AP_Standort_Planung T_ZO_REM_AP_Standort_Planung { get; set; }
    }
}
