//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ZO_AP_Raum_AP_Ref_Zuschlagsflaeche_Parkplatz
    {
        public System.Guid ZO_RMZFP_UID { get; set; }
        public System.Guid ZO_RMZFP_RM_UID { get; set; }
        public System.Guid ZO_RMZFP_PP_UID { get; set; }
        public System.DateTime ZO_RMZFP_DatumVon { get; set; }
        public System.DateTime ZO_RMZFP_DatumBis { get; set; }
        public int ZO_RMZFP_Status { get; set; }
    
        public virtual T_AP_Parkplatz T_AP_Parkplatz { get; set; }
        public virtual T_AP_Raum T_AP_Raum { get; set; }
    }
}
