//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ZO_AP_Zone_Flaeche
    {
        public System.Guid ZO_ZNFlaeche_UID { get; set; }
        public System.Guid ZO_ZNFlaeche_ZN_UID { get; set; }
        public Nullable<double> ZO_ZNFlaeche_Flaeche { get; set; }
        public System.DateTime ZO_ZNFlaeche_DatumVon { get; set; }
        public System.DateTime ZO_ZNFlaeche_DatumBis { get; set; }
        public int ZO_ZNFlaeche_Status { get; set; }
    
        public virtual T_AP_Zone T_AP_Zone { get; set; }
    }
}
