//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ZO_AP_Kommunikation_DWG
    {
        public System.Guid ZO_KMDWG_UID { get; set; }
        public System.Guid ZO_KMDWG_KM_UID { get; set; }
        public string ZO_KMDWG_ApertureDWG { get; set; }
        public System.DateTime ZO_KMDWG_DatumVon { get; set; }
        public System.DateTime ZO_KMDWG_DatumBis { get; set; }
        public string ZO_KMDWG_ApertureObjID { get; set; }
        public int ZO_KMDWG_Status { get; set; }
        public string ZO_KMDWG_DWGID { get; set; }
    
        public virtual T_AP_Kommunikation T_AP_Kommunikation { get; set; }
    }
}
