//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ZO_AP_Kunst_Werte
    {
        public System.Guid ZO_KUW_UID { get; set; }
        public int ZO_KUW_MDT_ID { get; set; }
        public System.Guid ZO_KUW_KU_UID { get; set; }
        public Nullable<System.Guid> ZO_KUW_KWKAT_UID { get; set; }
        public Nullable<System.DateTime> ZO_KUW_Datum { get; set; }
        public Nullable<double> ZO_KUW_Preis { get; set; }
        public string ZO_KUW_Bemerkung { get; set; }
        public Nullable<int> ZO_KUW_Status { get; set; }
    
        public virtual T_AP_Kunst T_AP_Kunst { get; set; }
        public virtual T_AP_Ref_KunstWerteKategorie T_AP_Ref_KunstWerteKategorie { get; set; }
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
    }
}
