//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ZO_SYS_Settings_AP_Ref_Mandant
    {
        public System.Guid ZO_SETMDT_UID { get; set; }
        public Nullable<System.Guid> ZO_SETMDT_SET_UID { get; set; }
        public int ZO_SETMDT_MDT_ID { get; set; }
        public string ZO_SETMDT_Wert { get; set; }
        public int ZO_SETMDT_Status { get; set; }
    
        public virtual T_AP_Ref_Mandant T_AP_Ref_Mandant { get; set; }
        public virtual T_SYS_Settings T_SYS_Settings { get; set; }
    }
}
