//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ZO_AP_Parkplatz_Reservation
    {
        public System.Guid ZO_PPRES_UID { get; set; }
        public System.DateTime ZO_PPRES_DatumVon { get; set; }
        public System.DateTime ZO_PPRES_DatumBis { get; set; }
        public System.DateTime ZO_PPRES_Created { get; set; }
        public int ZO_PPRES_Status { get; set; }
    
        public virtual T_AP_Parkplatz T_AP_Parkplatz { get; set; }
        public virtual T_Benutzer T_Benutzer { get; set; }
    }
}
