//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ZO_AP_Parkplatz_AV_Adressen
    {
        public System.Guid ZO_PPADR_UID { get; set; }
        public System.Guid ZO_PPADR_PP_UID { get; set; }
        public System.Guid ZO_PPADR_ADR_UID { get; set; }
        public System.DateTime ZO_PPADR_DatumVon { get; set; }
        public System.DateTime ZO_PPADR_DatumBis { get; set; }
        public int ZO_PPADR_Status { get; set; }
        public double ZO_PPADR_PreisM2 { get; set; }
        public double ZO_PPADR_Flaeche { get; set; }
        public double ZO_PPADR_Mietansatz { get; set; }
        public string ZO_PPADR_Schild { get; set; }
        public string ZO_PPADR_Bemerkung { get; set; }
        public double ZO_PPADR_FlaecheProzent { get; set; }
    
        public virtual T_AP_Parkplatz T_AP_Parkplatz { get; set; }
        public virtual T_AV_Adressen T_AV_Adressen { get; set; }
    }
}
