//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ZO_AP_Aussenobjekt_DWG
    {
        public System.Guid ZO_AODWG_UID { get; set; }
        public System.Guid ZO_AODWG_AO_UID { get; set; }
        public string ZO_AODWG_ApertureDWG { get; set; }
        public System.DateTime ZO_AODWG_DatumVon { get; set; }
        public System.DateTime ZO_AODWG_DatumBis { get; set; }
        public string ZO_AODWG_ApertureObjID { get; set; }
        public int ZO_AODWG_Status { get; set; }
        public string ZO_AODWG_DWGID { get; set; }
    
        public virtual T_AP_Aussenobjekt T_AP_Aussenobjekt { get; set; }
    }
}
