//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ZO_REM_AP_Raum_Raumgruppe
    {
        public System.Guid ZO_RMRG_UID { get; set; }
        public Nullable<System.Guid> ZO_RMRG_BB_UID { get; set; }
        public Nullable<System.Guid> ZO_RMRG_NA_UID { get; set; }
        public Nullable<System.Guid> ZO_RMRG_RP_UID { get; set; }
        public string ZO_RMRG_Name { get; set; }
        public string ZO_RMRG_Raumgruppe { get; set; }
        public System.DateTime ZO_RMRG_GueltigVon { get; set; }
        public System.DateTime ZO_RMRG_GueltigBis { get; set; }
        public int ZO_RMRG_Status { get; set; }
    
        public virtual T_AP_Ref_Bodenbelag T_AP_Ref_Bodenbelag { get; set; }
        public virtual T_AP_Ref_Nutzungsart T_AP_Ref_Nutzungsart { get; set; }
        public virtual T_AP_Ref_Reinigungsprio T_AP_Ref_Reinigungsprio { get; set; }
    }
}
