//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ZO_AP_Raum_Flaeche
    {
        public System.Guid ZO_RMFlaeche_UID { get; set; }
        public System.Guid ZO_RMFlaeche_RM_UID { get; set; }
        public Nullable<double> ZO_RMFlaeche_Flaeche { get; set; }
        public System.DateTime ZO_RMFlaeche_DatumVon { get; set; }
        public System.DateTime ZO_RMFlaeche_DatumBis { get; set; }
        public int ZO_RMFlaeche_Status { get; set; }
        public Nullable<double> ZO_RMFlaeche_Umfang { get; set; }
        public Nullable<double> ZO_RMFlaeche_Fenster { get; set; }
        public Nullable<double> ZO_RMFlaeche_Wand { get; set; }
    
        public virtual T_AP_Raum T_AP_Raum { get; set; }
    }
}
