//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ZO_TM_TSTA_TSK
    {
        public System.Guid TSTATSK_UID { get; set; }
        public System.Guid TSTATSK_TSK_UID { get; set; }
        public System.Guid TSTATSK_TSTA_UID { get; set; }
        public System.DateTime TSTATSK_Date { get; set; }
    
        public virtual T_TM_Ref_TaskStatus T_TM_Ref_TaskStatus { get; set; }
        public virtual T_TM_Tasks T_TM_Tasks { get; set; }
    }
}
