//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ZO_AP_Arbeitsplatz_AP_Ref_Kostenstelle
    {
        public System.Guid ZO_APKST_UID { get; set; }
        public System.DateTime ZO_APKST_DatumVon { get; set; }
        public System.DateTime ZO_APKST_DatumBis { get; set; }
        public int ZO_APKST_Status { get; set; }
        public double ZO_APKST_Preis { get; set; }
        public string ZO_APKST_Bemerkung { get; set; }
        public Nullable<double> ZO_APKST_FlaecheProz { get; set; }
    
        public virtual T_AP_Arbeitsplatz T_AP_Arbeitsplatz { get; set; }
        public virtual T_AP_Ref_Kostenstelle T_AP_Ref_Kostenstelle { get; set; }
    }
}
