//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDataFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ZO_TASK_Ref_Checkliste_Comment
    {
        public System.Guid ZO_TSKTCLCOMMENT_UID { get; set; }
        public Nullable<System.Guid> ZO_TSKTCLCOMMENT_TSK_UID { get; set; }
        public Nullable<System.Guid> ZO_TSKTCLCOMMENT_TCL_UID { get; set; }
        public string ZO_TSKTCLCOMMENT_Comment { get; set; }
        public Nullable<System.Guid> ZO_TSKTCLCOMMENT_TPL_UID { get; set; }
        public int ZO_TSKTCLCOMMENT_Status { get; set; }
    
        public virtual T_TM_Ref_Checkliste T_TM_Ref_Checkliste { get; set; }
        public virtual T_TM_Tasks T_TM_Tasks { get; set; }
        public virtual T_TM_Tasks_Planung T_TM_Tasks_Planung { get; set; }
    }
}
